//! Human-facing HTML (DESIGN.md §11).
//!
//! Four rules hold this together, and each one is load-bearing:
//!
//! - **Only a human reads it.** No agent opens one of these files back;
//!   everything an agent needs stays behind `--json`. The moment a page becomes
//!   agent input it starts costing tokens against the §13 budget, and the same
//!   content in HTML costs several times what the markdown it came from does.
//! - **One file, no network.** These open from `file://`, often over SSH or
//!   WSL. Every style and script is inline and nothing is fetched.
//! - **No control that changes state.** The page informs; the terminal decides.
//!   A button that approved a spec would make the terminal check in `gate.rs`
//!   meaningless, and that check is the only thing standing between an
//!   enthusiastic agent and its own approval.
//! - **Regenerated, never edited.** Hence the banner, and hence
//!   `.bevel/cache/`, which is already ignored by git.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use crate::project::Project;

/// One page. Callers build `body` from the helpers below and hand it over.
pub struct Page {
    pub title: String,
    pub subtitle: String,
    /// The command that regenerates this file, shown in the footer.
    pub regenerate: String,
    pub body: String,
}

impl Page {
    pub fn new(title: impl Into<String>, regenerate: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            subtitle: String::new(),
            regenerate: regenerate.into(),
            body: String::new(),
        }
    }

    pub fn subtitle(mut self, s: impl Into<String>) -> Self {
        self.subtitle = s.into();
        self
    }

    pub fn body(mut self, s: impl Into<String>) -> Self {
        self.body = s.into();
        self
    }

    pub fn render(&self) -> String {
        let sub = if self.subtitle.is_empty() {
            String::new()
        } else {
            format!("<p class=sub>{}</p>", escape(&self.subtitle))
        };
        format!(
            "<!doctype html>\n\
             <!-- Generated by bevel. Regenerate with `{}`; edits here are lost.\n\
             \x20    Read-only by design: nothing on this page can change project state. -->\n\
             <html lang=en><head><meta charset=utf-8>\n\
             <meta name=viewport content=\"width=device-width,initial-scale=1\">\n\
             <title>{}</title>\n<style>{CSS}</style>\n</head><body>\n\
             <header><h1>{}</h1>{sub}</header>\n\
             <main>{}</main>\n\
             <footer>Generated by bevel. <code>{}</code> regenerates it. \
             Nothing here changes state — the terminal decides.</footer>\n\
             </body></html>\n",
            escape(&self.regenerate),
            escape(&self.title),
            escape(&self.title),
            self.body,
            escape(&self.regenerate),
        )
    }
}

/// Write into `.bevel/cache/`, report the path, and optionally open it.
pub fn write(project: &Project, name: &str, page: &Page, open: bool) -> Result<PathBuf> {
    let dir = project.cache_dir();
    std::fs::create_dir_all(&dir)?;
    let path = dir.join(name);
    std::fs::write(&path, page.render())
        .with_context(|| format!("cannot write {}", path.display()))?;
    if open {
        launch(&path);
    }
    Ok(path)
}

/// Best effort. A viewer that will not start is not a reason to fail a report
/// that has already been written — the path is printed either way.
///
/// The empty argument on Windows is not a typo: `start` reads its first quoted
/// argument as a window title, so `start "C:\...\board.html"` opens an empty
/// console named after the file instead of the file.
fn launch(path: &Path) {
    let line = if cfg!(target_os = "macos") {
        format!("open {}", quote(&path.to_string_lossy()))
    } else if cfg!(windows) {
        format!("start \"\" {}", quote(&path.to_string_lossy()))
    } else {
        format!("xdg-open {}", quote(&path.to_string_lossy()))
    };
    let _ = crate::shell::command(&line)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();
}

fn quote(s: &str) -> String {
    if cfg!(windows) {
        format!("\"{s}\"")
    } else {
        format!("'{}'", s.replace('\'', r"'\''"))
    }
}

pub fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

/// Markdown as it is written in this repo: tables, task lists, strikethrough.
///
/// Raw HTML in the source is escaped rather than passed through. These files
/// are the project's own, so the risk is not injection but silent breakage —
/// the template comments in `spec.md` would otherwise vanish into the markup
/// and take the guidance they carry with them.
pub fn markdown(md: &str) -> String {
    use pulldown_cmark::{html, Options, Parser};
    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_TASKLISTS);
    options.insert(Options::ENABLE_FOOTNOTES);
    let mut out = String::new();
    html::push_html(&mut out, Parser::new_ext(md, options));
    out
}

/// A card: the unit every report is built from.
pub fn card(title: &str, body: &str) -> String {
    format!(
        "<section class=card><h2>{}</h2>{body}</section>\n",
        escape(title)
    )
}

/// A short coloured label. `kind` is a CSS class, not free text.
pub fn pill(kind: &str, text: &str) -> String {
    format!("<span class=\"pill {kind}\">{}</span>", escape(text))
}

/// A horizontal bar against a limit.
///
/// The limit sits at 71.4% of the track rather than at the end, so that going
/// over is drawn rather than clipped: a file at twice its budget and a file
/// three lines past it are not the same problem, and a full bar for both would
/// say they were.
pub fn meter(value: usize, limit: usize, label: &str) -> String {
    const LIMIT_AT: f64 = 71.4;
    let pct = (value as f64 / limit.max(1) as f64 * 100.0).min(140.0);
    format!(
        "<div class=meter><div class=\"fill{}\" style=\"width:{:.1}%\"></div>\
         <span class=marker></span></div><span class=meterlabel>{}</span>",
        if value > limit { " over" } else { "" },
        (pct * LIMIT_AT / 100.0).min(100.0),
        escape(label)
    )
}

/// A single bar split by composition, with its legend. Proportions only —
/// segments carry their own number in the legend rather than on the bar, which
/// stops the smallest slice from being an unreadable sliver of text.
pub fn stacked(parts: &[(&str, usize)]) -> String {
    let total: usize = parts.iter().map(|(_, n)| n).sum();
    if total == 0 {
        return String::new();
    }
    let bar: String = parts
        .iter()
        .enumerate()
        .filter(|(_, (_, n))| *n > 0)
        .map(|(i, (_, n))| {
            format!(
                "<i class=s{} style=\"width:{:.2}%\"></i>",
                i + 1,
                *n as f64 / total as f64 * 100.0
            )
        })
        .collect();
    let legend: String = parts
        .iter()
        .enumerate()
        .map(|(i, (label, n))| {
            format!(
                "<span><i class=s{}></i>{} — {n}</span>",
                i + 1,
                escape(label)
            )
        })
        .collect();
    format!("<div class=stack>{bar}</div><div class=legend>{legend}</div>")
}

/// An inline SVG line chart. Empty input yields an honest note rather than an
/// empty axis, because "no history" and "flat history" are different facts.
pub fn line_chart(points: &[(String, usize)], caption: &str) -> String {
    if points.len() < 2 {
        return format!(
            "<p class=empty>Not enough history to plot a trend yet ({} point{}).</p>",
            points.len(),
            if points.len() == 1 { "" } else { "s" }
        );
    }
    let (w, h) = (720.0_f64, 220.0_f64);
    let (pad_l, pad_b, pad_t) = (52.0_f64, 28.0_f64, 12.0_f64);
    let max = points.iter().map(|p| p.1).max().unwrap_or(1).max(1) as f64;
    let n = points.len() as f64;

    let x = |i: usize| pad_l + (w - pad_l - 8.0) * (i as f64) / (n - 1.0);
    let y = |v: usize| pad_t + (h - pad_t - pad_b) * (1.0 - v as f64 / max);

    let path: String = points
        .iter()
        .enumerate()
        .map(|(i, p)| {
            format!(
                "{}{:.1} {:.1}",
                if i == 0 { "M" } else { " L" },
                x(i),
                y(p.1)
            )
        })
        .collect();
    let area = format!(
        "{path} L{:.1} {:.1} L{:.1} {:.1} Z",
        x(points.len() - 1),
        h - pad_b,
        x(0),
        h - pad_b
    );

    let dots: String = points
        .iter()
        .enumerate()
        .map(|(i, p)| {
            format!(
                "<circle cx={:.1} cy={:.1} r=3><title>{} — {} lines</title></circle>",
                x(i),
                y(p.1),
                escape(&p.0),
                p.1
            )
        })
        .collect();

    // First and last only: a label per commit is unreadable past a dozen points.
    let first = &points[0].0;
    let last = &points[points.len() - 1].0;

    format!(
        "<figure class=chart><svg viewBox=\"0 0 {w} {h}\" role=img \
         aria-label=\"{}\"><path class=area d=\"{area}\"/>\
         <path class=line d=\"{path}\"/>{dots}\
         <line class=axis x1={pad_l} y1={:.1} x2={w} y2={:.1}/>\
         <text class=tick x=8 y={:.1}>{}</text>\
         <text class=tick x=8 y={:.1}>0</text>\
         <text class=tick x={pad_l} y={h} text-anchor=start>{}</text>\
         <text class=tick x={w} y={h} text-anchor=end>{}</text>\
         </svg><figcaption>{}</figcaption></figure>",
        escape(caption),
        h - pad_b,
        h - pad_b,
        pad_t + 4.0,
        max as usize,
        h - pad_b,
        escape(first),
        escape(last),
        escape(caption),
    )
}

const CSS: &str = "\
*{box-sizing:border-box}\
:root{--bg:#fbfbfa;--fg:#1a1a19;--dim:#6b6b66;--line:#e2e1dd;--card:#fff;\
--accent:#3b5bdb;--ok:#2f8f4e;--warn:#b3701a;--bad:#c0392b;--code:#f2f1ee}\
@media(prefers-color-scheme:dark){:root{--bg:#16161a;--fg:#e6e5e1;--dim:#96958e;\
--line:#2c2c31;--card:#1d1d22;--accent:#7b93f0;--ok:#5fbb7d;--warn:#d99a4a;\
--bad:#e07a6c;--code:#232329}}\
html{-webkit-text-size-adjust:100%}\
body{margin:0;background:var(--bg);color:var(--fg);\
font:15px/1.6 ui-sans-serif,system-ui,-apple-system,'Segoe UI',Roboto,sans-serif}\
header,main,footer{max-width:62rem;margin:0 auto;padding:0 1.5rem}\
header{padding-top:2.5rem;padding-bottom:.5rem}\
h1{font-size:1.65rem;margin:0;letter-spacing:-.01em}\
h2{font-size:1rem;margin:0 0 .9rem;text-transform:uppercase;letter-spacing:.07em;\
color:var(--dim);font-weight:600}\
h3{font-size:1rem;margin:1.4rem 0 .4rem}\
.sub{color:var(--dim);margin:.35rem 0 0}\
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;\
padding:1.25rem 1.4rem;margin:1.1rem 0}\
footer{color:var(--dim);font-size:.82rem;padding:2rem 1.5rem 3rem;\
border-top:1px solid var(--line);margin-top:2.5rem}\
code,pre{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.86em}\
code{background:var(--code);padding:.12em .38em;border-radius:4px}\
pre{background:var(--code);padding:.9rem 1rem;border-radius:8px;overflow-x:auto}\
pre code{background:none;padding:0}\
a{color:var(--accent)}\
table{border-collapse:collapse;width:100%;font-size:.92rem}\
.scroll{overflow-x:auto}\
th{text-align:left;font-weight:600;color:var(--dim);font-size:.78rem;\
text-transform:uppercase;letter-spacing:.05em;padding:.4rem .6rem;\
border-bottom:1px solid var(--line);white-space:nowrap}\
td{padding:.55rem .6rem;border-bottom:1px solid var(--line);vertical-align:top}\
tr:last-child td{border-bottom:none}\
.pill{display:inline-block;padding:.1em .55em;border-radius:99px;font-size:.74rem;\
font-weight:600;letter-spacing:.02em;border:1px solid transparent;white-space:nowrap}\
.a{background:color-mix(in srgb,var(--ok) 16%,transparent);color:var(--ok);\
border-color:color-mix(in srgb,var(--ok) 35%,transparent)}\
.b{background:color-mix(in srgb,var(--accent) 16%,transparent);color:var(--accent);\
border-color:color-mix(in srgb,var(--accent) 35%,transparent)}\
.c{background:color-mix(in srgb,var(--warn) 16%,transparent);color:var(--warn);\
border-color:color-mix(in srgb,var(--warn) 35%,transparent)}\
.bad{background:color-mix(in srgb,var(--bad) 16%,transparent);color:var(--bad);\
border-color:color-mix(in srgb,var(--bad) 35%,transparent)}\
.mute{background:var(--code);color:var(--dim);border-color:var(--line)}\
.empty{color:var(--dim);font-style:italic}\
.meter{position:relative;display:inline-block;width:10rem;height:9px;\
background:var(--code);border-radius:99px;overflow:hidden;vertical-align:middle}\
.meter .fill{position:absolute;left:0;top:0;bottom:0;background:var(--ok);border-radius:99px}\
.meter .fill.over{background:var(--bad)}\
.meter .marker{position:absolute;left:71.4%;top:0;bottom:0;width:1px;background:var(--dim);opacity:.55}\
.meterlabel{color:var(--dim);font-size:.8rem;margin-left:.5rem}\
.stack{display:flex;height:14px;border-radius:99px;overflow:hidden;\
background:var(--code);margin:.7rem 0 .5rem}\
.stack i{display:block;min-width:2px}\
.legend{display:flex;gap:1.2rem;flex-wrap:wrap;font-size:.8rem;color:var(--dim)}\
.legend i{display:inline-block;width:.6rem;height:.6rem;border-radius:2px;margin-right:.4rem}\
.s1{background:var(--accent)}\
.s2{background:color-mix(in srgb,var(--accent) 50%,var(--bg))}\
.s3{background:color-mix(in srgb,var(--dim) 40%,var(--bg))}\
.big{font-size:2.1rem;font-weight:600;letter-spacing:-.02em;line-height:1.1}\
.decision{border-bottom:1px solid var(--line);padding:.75rem 0}\
.decision:last-of-type{border-bottom:none}\
.decision .q{font-weight:600}\
.decision p{margin:.3rem 0 0}\
.rejected{color:var(--dim)}\
input[type=search]{width:100%;padding:.55rem .8rem;border:1px solid var(--line);\
border-radius:8px;background:var(--bg);color:var(--fg);font:inherit;font-size:.9rem}\
.graph{overflow-x:auto;padding-bottom:.3rem}\
.graph svg{display:block;margin-bottom:.5rem;max-width:100%;height:auto}\
.graph rect{fill:var(--bg);stroke:var(--line)}\
.graph .id{fill:var(--fg);font-size:13px;font-weight:600;\
font-family:ui-monospace,monospace}\
.graph .t{fill:var(--dim);font-size:11px}\
.graph .edge{stroke:var(--dim);stroke-width:1.5;fill:none}\
.graph .head{fill:var(--dim);stroke:none}\
.graph .lbl{fill:var(--dim);font-size:10.5px}\
.board{display:grid;grid-template-columns:repeat(auto-fit,minmax(11rem,1fr));gap:1rem}\
.col h3{font-size:.74rem;text-transform:uppercase;letter-spacing:.06em;\
color:var(--dim);margin:0 0 .6rem;display:flex;justify-content:space-between;\
border-bottom:1px solid var(--line);padding-bottom:.35rem}\
.count{font-variant-numeric:tabular-nums}\
.spec{background:var(--bg);border:1px solid var(--line);border-radius:8px;\
padding:.6rem .7rem;margin-bottom:.5rem;font-size:.86rem}\
.spec.reopened{border-color:var(--bad)}\
.spec b{font-variant-numeric:tabular-nums;color:var(--dim);margin-right:.35rem}\
.meta{color:var(--dim);font-size:.76rem;margin:.3rem 0 .4rem}\
.progress{height:5px;background:var(--code);border-radius:99px;overflow:hidden;\
margin-bottom:.3rem}\
.progress i{display:block;height:100%;background:var(--ok)}\
.chart{margin:0}\
.chart svg{width:100%;height:auto}\
.chart .area{fill:color-mix(in srgb,var(--accent) 14%,transparent)}\
.chart .line{fill:none;stroke:var(--accent);stroke-width:2}\
.chart circle{fill:var(--accent)}\
.chart .axis{stroke:var(--line)}\
.chart .tick{fill:var(--dim);font-size:11px}\
figcaption{color:var(--dim);font-size:.82rem;margin-top:.5rem}\
.kv{display:grid;grid-template-columns:auto 1fr;gap:.35rem 1.1rem;font-size:.92rem}\
.kv dt{color:var(--dim)}\
.kv dd{margin:0}\
.prose h1{font-size:1.25rem;margin:1.4rem 0 .5rem}\
.prose h2{font-size:1.05rem;text-transform:none;letter-spacing:0;color:var(--fg);\
margin:1.5rem 0 .5rem}\
.prose blockquote{margin:.8rem 0;padding-left:1rem;border-left:3px solid var(--line);\
color:var(--dim)}\
.warn{border-color:color-mix(in srgb,var(--bad) 45%,var(--line))}\
.warn h2{color:var(--bad)}\
.note{color:var(--dim);font-size:.86rem;margin:.4rem 0 0}\
.cmd{background:var(--code);border:1px solid var(--line);border-radius:8px;\
padding:.75rem 1rem;font-family:ui-monospace,monospace;font-size:.9rem;\
display:flex;justify-content:space-between;gap:1rem;align-items:center;flex-wrap:wrap}\
.cmd b{font-weight:600}\
.cmd span{color:var(--dim);font-family:inherit;font-size:.8rem}\
";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_page_is_self_contained_and_says_it_is_generated() {
        let html = Page::new("Report", "bevel review 7")
            .subtitle("0007 example")
            .body("<p>hi</p>")
            .render();
        assert!(html.starts_with("<!doctype html>"));
        assert!(html.contains("Generated by bevel"));
        assert!(html.contains("bevel review 7"));
        // No request may leave the page: it opens from file:// with no network.
        for probe in ["http://", "https://", "//cdn", "src=", "@import"] {
            assert!(!html.contains(probe), "external reference `{probe}`");
        }
    }

    /// The gate is a terminal check. A page that could act on the project would
    /// route around it, so the markup must not contain the means.
    #[test]
    fn a_page_carries_no_control_that_could_change_state() {
        let html = Page::new("Report", "bevel review 7")
            .body(card("Criteria", "<p>x</p>"))
            .render();
        for probe in ["<form", "<button", "<input", "onclick", "fetch("] {
            assert!(!html.contains(probe), "interactive control `{probe}`");
        }
    }

    #[test]
    fn markup_in_a_title_cannot_escape_into_the_page() {
        let html = Page::new("<script>alert(1)</script>", "bevel board").render();
        assert!(!html.contains("<script>alert"));
        assert!(html.contains("&lt;script&gt;"));
    }

    #[test]
    fn markdown_renders_the_forms_the_repo_actually_uses() {
        let out = markdown("# H\n\n| a | b |\n|---|---|\n| 1 | 2 |\n\n`code`\n");
        assert!(out.contains("<h1>H</h1>"));
        assert!(out.contains("<table>"));
        assert!(out.contains("<code>code</code>"));
    }

    #[test]
    fn a_trend_needs_two_points_before_it_claims_one() {
        assert!(line_chart(&[], "x").contains("Not enough history"));
        assert!(line_chart(&[("a".into(), 1)], "x").contains("Not enough history"));
        let two = line_chart(&[("a".into(), 1), ("b".into(), 9)], "harness lines");
        assert!(two.contains("<svg"));
        assert!(two.contains("harness lines"));
    }

    #[test]
    fn a_meter_past_its_limit_is_marked_rather_than_clipped() {
        assert!(meter(120, 50, "120/50").contains("over"));
        assert!(!meter(30, 50, "30/50").contains("over"));
    }
}
