//! `specs/README.md`, the generated index (DESIGN.md §3 and §11).
//!
//! This exists because `domain-scout` is told to read it *first* and it was
//! never generated — the highest-value scout opened a file that did not exist.
//! §11's answer to "what about a hundred specs?" also rests on it: the scout
//! reads one-line summaries here and opens only the specs that look relevant,
//! which is progressive disclosure applied to the project's own artifacts.

use anyhow::{Context, Result};
use std::path::PathBuf;

use crate::project::Project;
use crate::spec::{self, Criterion, Spec};

const MARKER: &str = "<!-- generated by bevel — run `bevel index` to refresh -->";
/// Long enough to be useful to a scout, short enough that rows stay readable.
const SUMMARY_LIMIT: usize = 110;

pub fn write(project: &Project) -> Result<PathBuf> {
    let specs = spec::all(&project.specs_dir())?;
    let path = project.specs_dir().join("README.md");
    std::fs::create_dir_all(project.specs_dir())?;
    std::fs::write(&path, render(&specs))
        .with_context(|| format!("cannot write {}", path.display()))?;
    Ok(path)
}

pub fn render(specs: &[Spec]) -> String {
    let mut out = format!("{MARKER}\n# Specs\n\n");

    if specs.is_empty() {
        out.push_str("None yet. `bevel inbox add \"…\"` then `bevel shape 1`.\n");
        return out;
    }

    out.push_str(
        "Read this before opening any spec: the summaries are here so you can \
         open only the ones that matter.\n\n\
         | id | status | title | summary | criteria | packages |\n\
         |---|---|---|---|---|---|\n",
    );

    for s in specs {
        out.push_str(&format!(
            "| [{}]({}/spec.md) | {} | {} | {} | {} | {} |\n",
            s.front.id,
            s.slug(),
            s.front.status,
            escape(&s.front.title),
            escape(&summary(s).unwrap_or_default()),
            criteria(s),
            if s.front.packages.is_empty() {
                "—".to_string()
            } else {
                escape(&s.front.packages.join(", "))
            }
        ));
    }

    // Supersession is the one relationship a reader cannot infer from the table.
    let links: Vec<String> = specs
        .iter()
        .flat_map(|s| {
            s.front
                .supersedes
                .iter()
                .map(move |sup| format!("- {} supersedes {}\n", s.front.id, sup.id))
        })
        .collect();
    if !links.is_empty() {
        out.push_str("\n## Supersessions\n\n");
        out.extend(links);
    }

    out
}

/// Tier counts, so a scout can see at a glance how bound a spec is.
fn criteria(s: &Spec) -> String {
    let (mut a, mut b, mut c) = (0, 0, 0);
    for cr in &s.front.acceptance {
        match cr {
            Criterion::A { .. } => a += 1,
            Criterion::B { .. } => b += 1,
            Criterion::C { .. } => c += 1,
        }
    }
    if a + b + c == 0 {
        return "none".into();
    }
    let mut parts = Vec::new();
    for (n, label) in [(a, 'A'), (b, 'B'), (c, 'C')] {
        if n > 0 {
            parts.push(format!("{n}{label}"));
        }
    }
    parts.join(" ")
}

/// The first real sentence under `## Problem`.
///
/// Skips the HTML comments the template ships, so an unfilled spec yields
/// nothing rather than echoing the instructions back at the reader.
fn summary(s: &Spec) -> Option<String> {
    let start = s.body.find("## Problem")? + "## Problem".len();
    let rest = &s.body[start..];

    let mut text = String::new();
    // The shipped template's guidance comment wraps onto a second line, so
    // skipping only lines that *start* with a marker leaks its prose into the
    // index. Track the block.
    let mut in_comment = false;
    for line in rest.lines() {
        let line = line.trim();
        if line.starts_with("##") {
            break; // Next section; Problem was empty.
        }
        if in_comment {
            if line.contains("-->") {
                in_comment = false;
            }
            continue;
        }
        if line.starts_with("<!--") {
            if !line.contains("-->") {
                in_comment = true;
            }
            continue;
        }
        if line.is_empty() {
            continue;
        }
        if !text.is_empty() {
            text.push(' ');
        }
        text.push_str(line);
        if text.len() >= SUMMARY_LIMIT || line.ends_with('.') {
            break;
        }
    }
    if text.is_empty() {
        return None;
    }
    if text.chars().count() > SUMMARY_LIMIT {
        text = text.chars().take(SUMMARY_LIMIT - 1).collect::<String>() + "…";
    }
    Some(text)
}

/// A pipe in a title would silently break the table.
fn escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project() -> (tempfile::TempDir, Project) {
        let tmp = tempfile::tempdir().unwrap();
        crate::project::init(tmp.path(), false).unwrap();
        let project = Project::discover_from(tmp.path()).unwrap();
        (tmp, project)
    }

    fn add(p: &Project, id: &str, slug: &str, front: &str, body: &str) {
        let dir = p.specs_dir().join(format!("{id}-{slug}"));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("spec.md"),
            format!(
                "---\nid: '{id}'\ntitle: Title {id}\nstatus: draft\nschema_version: 1\n\
                 created: '2026-08-03'\n{front}---\n{body}"
            ),
        )
        .unwrap();
    }

    #[test]
    fn an_empty_specs_directory_still_produces_a_usable_index() {
        let (_t, p) = project();
        let path = write(&p).unwrap();
        let text = std::fs::read_to_string(path).unwrap();
        assert!(text.starts_with(MARKER));
        assert!(text.contains("bevel shape 1"));
    }

    #[test]
    fn the_summary_comes_from_the_problem_section_not_the_template_comments() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "example",
            "acceptance: []\n",
            "# Title\n\n## Problem\n\n<!-- What is wrong today. -->\n\n\
             Uploads restart from zero after a dropped connection.\n\n## Appetite\n\ntwo days\n",
        );
        let specs = spec::all(&p.specs_dir()).unwrap();
        assert_eq!(
            summary(&specs[0]).unwrap(),
            "Uploads restart from zero after a dropped connection."
        );
    }

    #[test]
    fn an_unfilled_spec_yields_no_summary_rather_than_echoing_the_template() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "example",
            "acceptance: []\n",
            "# Title\n\n## Problem\n\n<!-- What is wrong today, in terms a user would\n\
             recognise. Not the solution. -->\n\n## Appetite\n",
        );
        let specs = spec::all(&p.specs_dir()).unwrap();
        assert!(summary(&specs[0]).is_none());
    }

    #[test]
    fn tier_counts_and_supersessions_are_visible() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "old",
            "acceptance:\n- tier: A\n  test: a\n",
            "# T\n\n## Problem\n\nOld behaviour.\n",
        );
        add(
            &p,
            "0002",
            "new",
            "supersedes:\n- id: '0001'\nacceptance:\n- tier: A\n  test: b\n\
             - tier: B\n  cmd: 'true'\n- tier: C\n  text: reads well\n\
             packages:\n- crates/core\n",
            "# T\n\n## Problem\n\nNew behaviour.\n",
        );

        let text = render(&spec::all(&p.specs_dir()).unwrap());
        assert!(text.contains("| 1A |"), "{text}");
        assert!(text.contains("| 1A 1B 1C |"), "{text}");
        assert!(text.contains("crates/core"));
        assert!(text.contains("0002 supersedes 0001"));
        // Links must be relative to specs/, since that is where the file lives.
        assert!(text.contains("[0001](0001-old/spec.md)"));
    }

    #[test]
    fn a_pipe_in_a_title_cannot_break_the_table() {
        let (_t, p) = project();
        let dir = p.specs_dir().join("0001-x");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("spec.md"),
            "---\nid: '0001'\ntitle: 'a | b'\nstatus: draft\nschema_version: 1\n\
             created: '2026-08-03'\nacceptance: []\n---\n# T\n\n## Problem\n\nx | y.\n",
        )
        .unwrap();
        let text = render(&spec::all(&p.specs_dir()).unwrap());
        for line in text.lines().filter(|l| l.starts_with("| [0001]")) {
            assert_eq!(line.matches(" | ").count(), 5, "row shape broke: {line}");
        }
    }

    #[test]
    fn a_long_problem_statement_is_truncated() {
        let (_t, p) = project();
        let long = "word ".repeat(60);
        add(
            &p,
            "0001",
            "x",
            "acceptance: []\n",
            &format!("# T\n\n## Problem\n\n{long}\n"),
        );
        let specs = spec::all(&p.specs_dir()).unwrap();
        let s = summary(&specs[0]).unwrap();
        assert!(s.chars().count() <= SUMMARY_LIMIT, "{}", s.chars().count());
        assert!(s.ends_with('…'));
    }
}
