//! `specs/README.md`, the generated index (DESIGN.md §3 and §11).
//!
//! This exists because `domain-scout` is told to read it *first* and it was
//! never generated — the highest-value scout opened a file that did not exist.
//! §11's answer to "what about a hundred specs?" also rests on it: the scout
//! reads one-line summaries here and opens only the specs that look relevant,
//! which is progressive disclosure applied to the project's own artifacts.

use anyhow::{Context, Result};
use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use crate::html::{self, card, pill, Page};
use crate::project::Project;
use crate::spec::{self, Criterion, DispositionAction, Spec, Status};

const MARKER: &str = "<!-- generated by bevel — run `bevel index` to refresh -->";
/// Long enough to be useful to a scout, short enough that rows stay readable.
const SUMMARY_LIMIT: usize = 110;

pub fn write(project: &Project) -> Result<PathBuf> {
    let specs = spec::all(&project.specs_dir())?;
    let path = project.specs_dir().join("README.md");
    std::fs::create_dir_all(project.specs_dir())?;
    std::fs::write(&path, render(&specs))
        .with_context(|| format!("cannot write {}", path.display()))?;
    Ok(path)
}

pub fn render(specs: &[Spec]) -> String {
    let mut out = format!("{MARKER}\n# Specs\n\n");

    if specs.is_empty() {
        out.push_str("None yet. `bevel inbox add \"…\"` then `bevel shape 1`.\n");
        return out;
    }

    out.push_str(
        "Read this before opening any spec: the summaries are here so you can \
         open only the ones that matter.\n\n\
         | id | status | title | summary | criteria | packages |\n\
         |---|---|---|---|---|---|\n",
    );

    for s in specs {
        out.push_str(&format!(
            "| [{}]({}/spec.md) | {} | {} | {} | {} | {} |\n",
            s.front.id,
            s.slug(),
            s.front.status,
            escape(&s.front.title),
            escape(&summary(s).unwrap_or_default()),
            criteria(s),
            if s.front.packages.is_empty() {
                "—".to_string()
            } else {
                escape(&s.front.packages.join(", "))
            }
        ));
    }

    // Supersession is the one relationship a reader cannot infer from the table.
    let links: Vec<String> = specs
        .iter()
        .flat_map(|s| {
            s.front
                .supersedes
                .iter()
                .map(move |sup| format!("- {} supersedes {}\n", s.front.id, sup.id))
        })
        .collect();
    if !links.is_empty() {
        out.push_str("\n## Supersessions\n\n");
        out.extend(links);
    }

    out
}

/// One answered question, lifted out of a spec's `decisions.md`.
///
/// The markdown stays canonical — `domain-scout` reads it, and nothing here is
/// ever read back by an agent. What this adds is the cross-spec view, which is
/// the one nobody has: `decisions.md` is per spec, and the question a person
/// actually asks six months later is *"what did we ever decide about auth, and
/// what did we turn down?"*.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Decision {
    pub spec: String,
    pub spec_title: String,
    pub date: String,
    pub question: String,
    pub answer: Option<String>,
    pub rejected: Option<String>,
}

/// Every decision across every spec, newest first.
pub fn decisions(specs: &[Spec]) -> Vec<Decision> {
    let mut out: Vec<Decision> = specs
        .iter()
        .flat_map(|s| {
            let text = std::fs::read_to_string(s.dir.join("decisions.md")).unwrap_or_default();
            parse_decisions(&text)
                .into_iter()
                .map(|(date, question, answer, rejected)| Decision {
                    spec: s.front.id.clone(),
                    spec_title: s.front.title.clone(),
                    date,
                    question,
                    answer,
                    rejected,
                })
                .collect::<Vec<_>>()
        })
        .collect();
    // Dates are ISO, so lexicographic order is chronological order.
    out.sort_by(|a, b| b.date.cmp(&a.date).then(a.spec.cmp(&b.spec)));
    out
}

/// `## <date> — <question>` blocks, with the `**Answer:**` and `**Rejected:**`
/// lines the template asks for. Entries inside HTML comments are skipped: the
/// template ships its own example commented out, and echoing it back as a real
/// decision would be worse than showing nothing.
fn parse_decisions(text: &str) -> Vec<(String, String, Option<String>, Option<String>)> {
    let mut out = Vec::new();
    let mut current: Option<(String, String, Option<String>, Option<String>)> = None;
    let mut in_comment = false;

    for line in text.lines() {
        let trimmed = line.trim();
        if in_comment {
            in_comment = !trimmed.contains("-->");
            continue;
        }
        if trimmed.starts_with("<!--") {
            in_comment = !trimmed.contains("-->");
            continue;
        }
        if let Some(heading) = trimmed.strip_prefix("## ") {
            if let Some(entry) = current.take() {
                out.push(entry);
            }
            let (date, question) = match heading.split_once('—') {
                Some((d, q)) => (d.trim().to_string(), q.trim().to_string()),
                None => (String::new(), heading.trim().to_string()),
            };
            current = Some((date, question, None, None));
            continue;
        }
        let Some(entry) = current.as_mut() else {
            continue;
        };
        if let Some(v) = field(trimmed, "Answer") {
            entry.2 = Some(v);
        } else if let Some(v) = field(trimmed, "Rejected") {
            entry.3 = Some(v);
        }
    }
    out.extend(current);
    out
}

fn field(line: &str, name: &str) -> Option<String> {
    let value = line
        .strip_prefix(&format!("**{name}:**"))
        .or_else(|| line.strip_prefix(&format!("**{name}**:")))?
        .trim();
    (!value.is_empty()).then(|| value.to_string())
}

/// Tier counts, so a scout can see at a glance how bound a spec is.
fn criteria(s: &Spec) -> String {
    let (mut a, mut b, mut c) = (0, 0, 0);
    for cr in &s.front.acceptance {
        match cr {
            Criterion::A { .. } => a += 1,
            Criterion::B { .. } => b += 1,
            Criterion::C { .. } => c += 1,
        }
    }
    if a + b + c == 0 {
        return "none".into();
    }
    let mut parts = Vec::new();
    for (n, label) in [(a, 'A'), (b, 'B'), (c, 'C')] {
        if n > 0 {
            parts.push(format!("{n}{label}"));
        }
    }
    parts.join(" ")
}

/// The first real sentence under `## Problem`.
///
/// Skips the HTML comments the template ships, so an unfilled spec yields
/// nothing rather than echoing the instructions back at the reader.
fn summary(s: &Spec) -> Option<String> {
    let start = s.body.find("## Problem")? + "## Problem".len();
    let rest = &s.body[start..];

    let mut text = String::new();
    // The shipped template's guidance comment wraps onto a second line, so
    // skipping only lines that *start* with a marker leaks its prose into the
    // index. Track the block.
    let mut in_comment = false;
    for line in rest.lines() {
        let line = line.trim();
        if line.starts_with("##") {
            break; // Next section; Problem was empty.
        }
        if in_comment {
            if line.contains("-->") {
                in_comment = false;
            }
            continue;
        }
        if line.starts_with("<!--") {
            if !line.contains("-->") {
                in_comment = true;
            }
            continue;
        }
        if line.is_empty() {
            continue;
        }
        if !text.is_empty() {
            text.push(' ');
        }
        text.push_str(line);
        if text.len() >= SUMMARY_LIMIT || line.ends_with('.') {
            break;
        }
    }
    if text.is_empty() {
        return None;
    }
    if text.chars().count() > SUMMARY_LIMIT {
        text = text.chars().take(SUMMARY_LIMIT - 1).collect::<String>() + "…";
    }
    Some(text)
}

/// A pipe in a title would silently break the table.
fn escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// The human half of the index: the decision log across every spec, and the
/// supersession graph.
///
/// Both answer questions the markdown index structurally cannot. A decision log
/// is per spec, so "what did we decide about this, ever" has nowhere to be
/// asked. And a supersession is a graph whose edges are labelled per acceptance
/// criterion — three hops of that in a bulleted list is unreadable, and this
/// project intends to still be running in six months.
pub fn render_html(specs: &[Spec]) -> Page {
    let mut body = String::new();

    let rows: String = specs
        .iter()
        .map(|s| {
            format!(
                "<tr><td><a href=\"../../{}/{}/spec.md\"><code>{}</code></a></td>\
                 <td>{}</td><td>{}</td><td>{}</td></tr>",
                // The index lives in `.bevel/cache/`; the specs do not.
                html::escape(
                    &s.dir
                        .parent()
                        .and_then(|p| p.file_name())
                        .map_or_else(|| "specs".to_string(), |n| n.to_string_lossy().into_owned())
                ),
                html::escape(&s.slug()),
                html::escape(&s.front.id),
                pill(status_class(s.front.status), s.front.status.as_str()),
                html::escape(&s.front.title),
                html::escape(&summary(s).unwrap_or_default()),
            )
        })
        .collect();
    body.push_str(&card(
        "Specs",
        &if specs.is_empty() {
            "<p class=empty>None yet.</p>".to_string()
        } else {
            format!(
                "<div class=scroll><table><tr><th>id</th><th>status</th><th>title</th>\
                 <th>summary</th></tr>{rows}</table></div>"
            )
        },
    ));

    body.push_str(&decisions_card(&decisions(specs)));
    body.push_str(&supersessions_card(specs));

    Page::new("Specs index", "bevel index --html")
        .subtitle("What was decided, and what replaced what")
        .body(body)
}

fn decisions_card(all: &[Decision]) -> String {
    if all.is_empty() {
        return card(
            "Decisions",
            "<p class=empty>No decisions recorded yet. They accumulate one interview \
             question at a time, and they are the only record of what you turned down.</p>",
        );
    }

    let rows: String = all
        .iter()
        .map(|d| {
            let searchable = format!(
                "{} {} {} {} {}",
                d.spec,
                d.spec_title,
                d.question,
                d.answer.as_deref().unwrap_or(""),
                d.rejected.as_deref().unwrap_or("")
            )
            .to_lowercase();
            format!(
                "<div class=decision data-t=\"{}\"><div class=q>{}</div>\
                 <div class=meta>{} · spec {} {}</div>{}{}</div>",
                html::escape(&searchable),
                html::escape(&d.question),
                html::escape(&d.date),
                html::escape(&d.spec),
                html::escape(&d.spec_title),
                d.answer
                    .as_deref()
                    .map(|a| format!("<p>{}</p>", html::escape(a)))
                    .unwrap_or_default(),
                d.rejected
                    .as_deref()
                    .map(|r| format!("<p class=rejected><b>Rejected:</b> {}</p>", html::escape(r)))
                    .unwrap_or_default(),
            )
        })
        .collect();

    // Presentation only: it hides rows, it touches nothing on disk. Without
    // JavaScript every row simply stays visible, which is the correct fallback.
    let script = "<script>\
        const q=document.getElementById('q');\
        q.addEventListener('input',()=>{\
        const v=q.value.trim().toLowerCase();\
        let n=0;\
        for(const el of document.querySelectorAll('.decision')){\
        const hit=!v||el.dataset.t.includes(v);el.hidden=!hit;if(hit)n++;}\
        document.getElementById('n').textContent=n;});\
        </script>";

    card(
        "Decisions",
        &format!(
            "<input id=q type=search placeholder=\"filter — try a word from a rejected \
             alternative\" autocomplete=off>\
             <p class=note><span id=n>{}</span> of {} shown</p>{rows}{script}",
            all.len(),
            all.len()
        ),
    )
}

fn supersessions_card(specs: &[Spec]) -> String {
    let chains = chains(specs);
    if chains.is_empty() {
        return String::new();
    }
    let titles: BTreeMap<&str, &str> = specs
        .iter()
        .map(|s| (s.front.id.as_str(), s.front.title.as_str()))
        .collect();
    let graphs: String = chains
        .iter()
        .map(|chain| draw_chain(chain, &titles))
        .collect();
    card(
        "Supersessions",
        &format!(
            "<div class=graph>{graphs}</div>\
             <p class=note>Each arrow carries what happened to the old spec's tier A \
             criteria. A dropped criterion is a passing test deleted on purpose, which \
             is why <code>validate</code> makes it carry a written reason.</p>"
        ),
    )
}

/// Paths through the supersession graph, one per branch.
///
/// Not merely an edge list: superseding is how a decision gets revisited, and
/// the readable question is "what did this become in the end", which is a path.
fn chains(specs: &[Spec]) -> Vec<Vec<(String, String)>> {
    let mut next: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    let mut has_parent: BTreeSet<String> = BTreeSet::new();
    let mut nodes: BTreeSet<String> = BTreeSet::new();

    for s in specs {
        for sup in &s.front.supersedes {
            nodes.insert(sup.id.clone());
            nodes.insert(s.front.id.clone());
            has_parent.insert(s.front.id.clone());
            next.entry(sup.id.clone())
                .or_default()
                .push((s.front.id.clone(), dispositions(sup)));
        }
    }

    let mut out = Vec::new();
    for root in nodes.iter().filter(|n| !has_parent.contains(*n)) {
        walk(
            root,
            &next,
            &mut vec![(root.clone(), String::new())],
            &mut out,
        );
    }
    out
}

fn walk(
    node: &str,
    next: &BTreeMap<String, Vec<(String, String)>>,
    path: &mut Vec<(String, String)>,
    out: &mut Vec<Vec<(String, String)>>,
) {
    match next.get(node) {
        None => out.push(path.clone()),
        Some(children) => {
            for (child, label) in children {
                // A cycle cannot happen through legal use, but a hand-edited
                // frontmatter can produce one and it must not hang the report.
                if path.iter().any(|(n, _)| n == child) {
                    out.push(path.clone());
                    continue;
                }
                path.push((child.clone(), label.clone()));
                walk(child, next, path, out);
                path.pop();
            }
        }
    }
}

fn dispositions(sup: &crate::spec::Supersession) -> String {
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for d in &sup.dispositions {
        *counts
            .entry(match d.action {
                DispositionAction::Inherited => "inherited",
                DispositionAction::Replaced => "replaced",
                DispositionAction::Dropped => "dropped",
            })
            .or_default() += 1;
    }
    if counts.is_empty() {
        return "no dispositions recorded".into();
    }
    counts
        .iter()
        .map(|(k, n)| format!("{n} {k}"))
        .collect::<Vec<_>>()
        .join(" · ")
}

/// One chain as an SVG row, oldest on the left.
fn draw_chain(chain: &[(String, String)], titles: &BTreeMap<&str, &str>) -> String {
    const BOX_W: f64 = 152.0;
    const BOX_H: f64 = 46.0;
    const GAP: f64 = 108.0;
    let width = chain.len() as f64 * (BOX_W + GAP) - GAP;
    let height = BOX_H + 26.0;

    let mut parts = String::new();
    for (i, (id, label)) in chain.iter().enumerate() {
        let x = i as f64 * (BOX_W + GAP);
        parts.push_str(&format!(
            "<rect x={x:.0} y=22 width={BOX_W:.0} height={BOX_H:.0} rx=7/>\
             <text class=id x={:.0} y=41>{}</text>\
             <text class=t x={:.0} y=57>{}</text>",
            x + 11.0,
            html::escape(id),
            x + 11.0,
            html::escape(&clip(
                titles.get(id.as_str()).copied().unwrap_or("(missing)"),
                20
            )),
        ));
        if i > 0 {
            let from = x - GAP;
            parts.push_str(&format!(
                "<path class=edge d=\"M{:.0} 45 L{:.0} 45\"/>\
                 <path class=head d=\"M{:.0} 45 l-7 -4 l0 8 z\"/>\
                 <text class=lbl x={:.0} y=16 text-anchor=middle>{}</text>",
                from,
                x - 7.0,
                x,
                from + GAP / 2.0,
                html::escape(label),
            ));
        }
    }

    format!(
        "<svg viewBox=\"0 0 {width:.0} {height:.0}\" width={width:.0} role=img \
         aria-label=\"supersession chain\">{parts}</svg>"
    )
}

fn clip(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    s.chars().take(max - 1).collect::<String>() + "…"
}

fn status_class(s: Status) -> &'static str {
    match s {
        Status::Draft | Status::Superseded => "mute",
        Status::Review => "c",
        Status::Approved | Status::Implementing => "b",
        Status::Done => "a",
    }
}

pub fn write_html(project: &Project, open: bool) -> Result<PathBuf> {
    let specs = spec::all(&project.specs_dir())?;
    html::write(project, "index.html", &render_html(&specs), open)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project() -> (tempfile::TempDir, Project) {
        let tmp = tempfile::tempdir().unwrap();
        crate::project::init(tmp.path(), false).unwrap();
        let project = Project::discover_from(tmp.path()).unwrap();
        (tmp, project)
    }

    fn add(p: &Project, id: &str, slug: &str, front: &str, body: &str) {
        let dir = p.specs_dir().join(format!("{id}-{slug}"));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("spec.md"),
            format!(
                "---\nid: '{id}'\ntitle: Title {id}\nstatus: draft\nschema_version: 1\n\
                 created: '2026-08-03'\n{front}---\n{body}"
            ),
        )
        .unwrap();
    }

    #[test]
    fn an_empty_specs_directory_still_produces_a_usable_index() {
        let (_t, p) = project();
        let path = write(&p).unwrap();
        let text = std::fs::read_to_string(path).unwrap();
        assert!(text.starts_with(MARKER));
        assert!(text.contains("bevel shape 1"));
    }

    #[test]
    fn the_summary_comes_from_the_problem_section_not_the_template_comments() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "example",
            "acceptance: []\n",
            "# Title\n\n## Problem\n\n<!-- What is wrong today. -->\n\n\
             Uploads restart from zero after a dropped connection.\n\n## Appetite\n\ntwo days\n",
        );
        let specs = spec::all(&p.specs_dir()).unwrap();
        assert_eq!(
            summary(&specs[0]).unwrap(),
            "Uploads restart from zero after a dropped connection."
        );
    }

    #[test]
    fn an_unfilled_spec_yields_no_summary_rather_than_echoing_the_template() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "example",
            "acceptance: []\n",
            "# Title\n\n## Problem\n\n<!-- What is wrong today, in terms a user would\n\
             recognise. Not the solution. -->\n\n## Appetite\n",
        );
        let specs = spec::all(&p.specs_dir()).unwrap();
        assert!(summary(&specs[0]).is_none());
    }

    #[test]
    fn tier_counts_and_supersessions_are_visible() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "old",
            "acceptance:\n- tier: A\n  test: a\n",
            "# T\n\n## Problem\n\nOld behaviour.\n",
        );
        add(
            &p,
            "0002",
            "new",
            "supersedes:\n- id: '0001'\nacceptance:\n- tier: A\n  test: b\n\
             - tier: B\n  cmd: 'true'\n- tier: C\n  text: reads well\n\
             packages:\n- crates/core\n",
            "# T\n\n## Problem\n\nNew behaviour.\n",
        );

        let text = render(&spec::all(&p.specs_dir()).unwrap());
        assert!(text.contains("| 1A |"), "{text}");
        assert!(text.contains("| 1A 1B 1C |"), "{text}");
        assert!(text.contains("crates/core"));
        assert!(text.contains("0002 supersedes 0001"));
        // Links must be relative to specs/, since that is where the file lives.
        assert!(text.contains("[0001](0001-old/spec.md)"));
    }

    #[test]
    fn a_pipe_in_a_title_cannot_break_the_table() {
        let (_t, p) = project();
        let dir = p.specs_dir().join("0001-x");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("spec.md"),
            "---\nid: '0001'\ntitle: 'a | b'\nstatus: draft\nschema_version: 1\n\
             created: '2026-08-03'\nacceptance: []\n---\n# T\n\n## Problem\n\nx | y.\n",
        )
        .unwrap();
        let text = render(&spec::all(&p.specs_dir()).unwrap());
        for line in text.lines().filter(|l| l.starts_with("| [0001]")) {
            assert_eq!(line.matches(" | ").count(), 5, "row shape broke: {line}");
        }
    }

    #[test]
    fn the_decision_log_is_gathered_across_specs_with_its_rejections() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "auth",
            "acceptance: []\n",
            "# T\n\n## Problem\n\nx.\n",
        );
        add(
            &p,
            "0002",
            "sync",
            "acceptance: []\n",
            "# T\n\n## Problem\n\ny.\n",
        );
        std::fs::write(
            p.specs_dir().join("0001-auth/decisions.md"),
            "# Decisions\n\n<!-- ## <date> — <question>\n     **Answer:** ... -->\n\n\
             ## 2026-08-01 — Sessions or tokens?\n\n**Answer:** Tokens, they survive a restart.\n\
             **Rejected:** Server sessions because two hosts would need sticky routing.\n",
        )
        .unwrap();
        std::fs::write(
            p.specs_dir().join("0002-sync/decisions.md"),
            "## 2026-08-04 — Last write wins?\n\n**Answer:** No, prefer local.\n",
        )
        .unwrap();

        let all = decisions(&spec::all(&p.specs_dir()).unwrap());
        assert_eq!(
            all.len(),
            2,
            "the commented template must not count: {all:?}"
        );
        // Newest first.
        assert_eq!(all[0].question, "Last write wins?");
        assert_eq!(all[1].spec, "0001");
        assert_eq!(
            all[1].rejected.as_deref(),
            Some("Server sessions because two hosts would need sticky routing.")
        );

        let html = render_html(&spec::all(&p.specs_dir()).unwrap()).render();
        assert!(html.contains("sticky routing"));
        assert!(html.contains("type=search"), "the log is searchable");
    }

    #[test]
    fn a_supersession_chain_is_drawn_with_what_happened_to_each_criterion() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "first",
            "acceptance:\n- tier: A\n  test: old_one\n",
            "# T\n\n## Problem\n\nx.\n",
        );
        add(
            &p,
            "0002",
            "second",
            "supersedes:\n- id: '0001'\n  dispositions:\n  - test: old_one\n    action: dropped\n\
                 note: the feature went away\nacceptance:\n- tier: A\n  test: new_one\n",
            "# T\n\n## Problem\n\ny.\n",
        );
        add(
            &p,
            "0003",
            "third",
            "supersedes:\n- id: '0002'\n  dispositions:\n  - test: new_one\n    action: inherited\n\
             acceptance:\n- tier: A\n  test: new_one\n",
            "# T\n\n## Problem\n\nz.\n",
        );

        let specs = spec::all(&p.specs_dir()).unwrap();
        let chains = chains(&specs);
        assert_eq!(chains.len(), 1, "one chain: {chains:?}");
        assert_eq!(
            chains[0]
                .iter()
                .map(|(id, _)| id.as_str())
                .collect::<Vec<_>>(),
            vec!["0001", "0002", "0003"]
        );

        let html = render_html(&specs).render();
        assert!(html.contains("1 dropped"));
        assert!(html.contains("1 inherited"));
        assert!(html.contains("<svg"));
    }

    /// Hand-edited frontmatter can describe a loop. The report must come back.
    #[test]
    fn a_cycle_in_supersessions_does_not_hang_the_report() {
        let (_t, p) = project();
        add(
            &p,
            "0001",
            "a",
            "supersedes:\n- id: '0002'\nacceptance: []\n",
            "# T\n\n## Problem\n\nx.\n",
        );
        add(
            &p,
            "0002",
            "b",
            "supersedes:\n- id: '0001'\nacceptance: []\n",
            "# T\n\n## Problem\n\ny.\n",
        );
        let specs = spec::all(&p.specs_dir()).unwrap();
        // Every node has a parent, so there is no root and nothing to draw —
        // but reaching that conclusion must terminate.
        assert!(chains(&specs).is_empty());
        assert!(render_html(&specs).render().contains("Specs index"));
    }

    #[test]
    fn a_long_problem_statement_is_truncated() {
        let (_t, p) = project();
        let long = "word ".repeat(60);
        add(
            &p,
            "0001",
            "x",
            "acceptance: []\n",
            &format!("# T\n\n## Problem\n\n{long}\n"),
        );
        let specs = spec::all(&p.specs_dir()).unwrap();
        let s = summary(&specs[0]).unwrap();
        assert!(s.chars().count() <= SUMMARY_LIMIT, "{}", s.chars().count());
        assert!(s.ends_with('…'));
    }
}
