//! Installing the method where each agent reads it (DESIGN.md §9).
//!
//! Two agents, and the split between them is known rather than guessed — which
//! was the condition set when five speculative renderers were deleted from this
//! file. What arrived with the second agent was not a fifth of a pattern but
//! the observation that agents differ *per resource kind*, not wholesale:
//! opencode scans `~/.claude/skills` and needs no skill rendering at all, and
//! has no `.claude/agents` fallback so needs every subagent translated. Hence
//! one trait per kind rather than one renderer per agent.
//!
//! A third agent will not fit these traits exactly, and that is expected: they
//! are internal, promise nothing, and the third is free to reshape them.
//!
//! **`AGENTS.md` and `CLAUDE.md` are not among the kinds.** They were, and the
//! removal is the load-bearing decision in this file: sync writes into `~` and
//! into `.claude/settings.json`, which are configuration, and it stopped
//! writing the two files that are *prose a project owns about itself*. Every
//! sharp edge that file ever had came from that confusion — a byte comparison
//! standing in for a missing marker, a migration that relocated a user's own
//! writing, a symlink that had to be detected before it was followed, and a
//! seed frozen against improvement because it doubled as the fingerprint of
//! what shipped years earlier. `bevel notes` prints the markdown to stdout and
//! the user applies it or does not. Nothing to classify, nothing to migrate,
//! nothing to clobber.
//!
//! What was never agent-specific survives untouched: the method has one source
//! on disk, and `bevel method show shape` prints it. Only the *frontmatter* of a
//! subagent is transliterated; no instruction text is ever copied into anyone's
//! prompt format, so there is still nothing to drift.

use anyhow::{bail, Context, Result};
use serde_json::{json, Map, Value};
use std::path::{Path, PathBuf};

use crate::method::Source;
use crate::paths::Layers;
use crate::project::Project;

/// Method file names. The bodies live in the method tree on disk, not here:
/// editing a skill must never require a release (DESIGN.md §2).
/// `shape` and `implement` are the lifecycle; the `*-architecture` ones are
/// conventions skills, loaded by the model when the work matches them rather
/// than by a step of the loop. Both kinds install the same way.
///
/// `skill-creator` is vendored from <https://github.com/anthropics/skills> under
/// the Apache License 2.0, and is the reason a skill is a directory rather than
/// a file: it ships scripts and reference documents its SKILL.md calls out to.
pub const SKILLS: [&str; 5] = [
    "shape",
    "implement",
    "rust-architecture",
    "angular-architecture",
    "skill-creator",
];

/// Skills vendored from somewhere else rather than written here.
///
/// The context budget measures these but does not fail on them (DESIGN.md §13).
/// That budget exists to stop *our* markdown from sprawling, and its remedy is
/// deletion. Neither half applies to a file we did not write: the length is not
/// ours to set, and the only real lever is whether to vendor the skill at all.
/// `bevel context` still prints the number, so the cost stays visible.
pub const VENDORED_SKILLS: [&str; 1] = ["skill-creator"];

pub fn is_vendored(skill: &str) -> bool {
    VENDORED_SKILLS.contains(&skill)
}

/// Subagents exist for context isolation: three independent searches that must
/// not pollute the context where the interview happens, and two reviewers that
/// must not have written what they review (DESIGN.md §6, §8).
pub const AGENT_DEFS: [&str; 7] = [
    "domain-scout",
    "risk-scout",
    "unknowns-scout",
    "spec-critic",
    "diff-reviewer",
    "context-packer",
    "mockup-builder",
];

const MARKER: &str = "<!-- generated by bevel — edit the method layer, not this file -->";
const DENY_RULE: &str = "Bash(bevel approve*)";
/// What this tool installed when it was called `harness`. Recognised so that a
/// rename cleans up after itself instead of leaving both generations in place.
const LEGACY_DENY_RULE: &str = "Bash(harness approve*)";
const COMMAND_PREFIXES: [&str; 2] = ["bevel ", "harness "];

// ------------------------------------------------------------------ actions

/// What a sync did to one file.
///
/// There is no `Moved` variant, and its absence is the invariant: sync only
/// ever touches files it generates, so it never has a user's own content in
/// its hands to relocate.
#[derive(Debug, PartialEq, Eq)]
pub enum Action {
    Wrote(String),
    Removed(String),
    Skipped(String, &'static str),
}

impl std::fmt::Display for Action {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Action::Wrote(p) => write!(f, "  wrote   {p}"),
            Action::Removed(p) => write!(f, "  removed {p}"),
            Action::Skipped(p, why) => write!(f, "  skipped {p} ({why})"),
        }
    }
}

// ------------------------------------------------------------------- agents

/// The agents bevel renders for.
///
/// Two, and a third is a decision rather than a line: the traits below took
/// their shape from these two, and a third will ask questions neither did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Agent {
    Claude,
    Opencode,
}

impl Agent {
    pub const ALL: [Agent; 2] = [Agent::Claude, Agent::Opencode];

    pub fn as_str(self) -> &'static str {
        match self {
            Agent::Claude => "claude",
            Agent::Opencode => "opencode",
        }
    }

    /// A directory whose presence suggests this agent is installed.
    fn marker(self, layers: &Layers) -> PathBuf {
        match self {
            Agent::Claude => layers.claude_home(),
            Agent::Opencode => layers.opencode_home(),
        }
    }

    /// An unsupported name is an error, never a silent no-op.
    ///
    /// The deleted multi-agent code accepted `codex` and `opencode` and then
    /// rendered nothing for either, which reads as success and is not. Naming
    /// what is supported costs one line and saves that whole class of report.
    pub fn parse(name: &str) -> Result<Self> {
        let want = name.trim().to_ascii_lowercase();
        Agent::ALL
            .into_iter()
            .find(|a| a.as_str() == want)
            .ok_or_else(|| {
                anyhow::anyhow!(
                    "unknown agent `{name}`\n  bevel renders for: {}",
                    Agent::ALL
                        .iter()
                        .map(|a| a.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            })
    }

    fn skills(self) -> &'static dyn SkillTarget {
        match self {
            Agent::Claude => &ClaudeCode,
            Agent::Opencode => &OpenCode,
        }
    }

    fn subagents(self) -> &'static dyn SubagentTarget {
        match self {
            Agent::Claude => &ClaudeCode,
            Agent::Opencode => &OpenCode,
        }
    }
}

/// Which agents to render for, when the user did not say.
///
/// Additive: two installed means both rendered. Falling back to Claude Code
/// rather than to nothing keeps a fresh machine — where neither directory
/// exists yet — from installing nothing at all and reporting success.
pub fn detect(layers: &Layers) -> Vec<Agent> {
    let found: Vec<Agent> = Agent::ALL
        .into_iter()
        .filter(|a| a.marker(layers).is_dir())
        .collect();
    if found.is_empty() {
        vec![Agent::Claude]
    } else {
        found
    }
}

// -------------------------------------------------------------- the targets

/// What every renderer needs, bundled so the traits take one argument.
struct Cx<'a> {
    project: Option<&'a Project>,
    layers: &'a Layers,
    source: &'a Source,
}

/// One trait per resource kind rather than one trait with three methods, so
/// that adding an agent forces an answer to each question separately instead
/// of inheriting a default nobody considered for it.
trait SkillTarget {
    /// Where this agent loads skills from. Two agents may name the same
    /// directory, and `sync` installs into it once.
    fn skills_dir(&self, cx: &Cx) -> PathBuf;
}

trait SubagentTarget {
    /// Where this agent loads subagent definitions from. Separate from
    /// `subagents` so `doctor` reports the directory the renderer will
    /// actually use, rather than a second copy of the same mapping that can
    /// drift from it.
    fn subagents_dir(&self, cx: &Cx) -> PathBuf;
    fn subagents(&self, cx: &Cx) -> Result<Vec<Action>>;
}

struct ClaudeCode;
struct OpenCode;

/// Install the method.
///
/// `project` is optional because half of this does not belong to a project.
/// What lands in `~/.claude` is the same text on the machine whatever directory
/// you are standing in, so requiring a project first would be a made-up
/// dependency — and one that bites exactly at the moment a new machine has no
/// projects yet.
pub fn sync(
    project: Option<&Project>,
    layers: &Layers,
    source: &Source,
    agents: &[Agent],
    hooks: bool,
) -> Result<Vec<Action>> {
    if !source.is_usable() {
        bail!("{}", crate::method::missing_help(source, layers));
    }
    let cx = Cx {
        project,
        layers,
        source,
    };
    let mut actions = Vec::new();

    // Skills first, and once per destination however many agents share it.
    // opencode reads Claude Code's directory, so `--agent opencode` alone still
    // has to install there — nothing else writes it, and the two skills that
    // are the pipeline would otherwise exist nowhere.
    let mut installed_into: Vec<PathBuf> = Vec::new();
    for agent in agents {
        let dir = agent.skills().skills_dir(&cx);
        if installed_into.contains(&dir) {
            continue;
        }
        actions.extend(install_skills(&dir, &cx)?);
        installed_into.push(dir);
    }

    for agent in agents {
        actions.extend(agent.subagents().subagents(&cx)?);
    }

    // Project-scoped on purpose, unlike everything above: these hooks shell out
    // to `bevel`, and at user level they would fire in every repository on the
    // machine, including those with no project to find. Claude Code only —
    // opencode expresses the same thing as a JavaScript plugin, which is a
    // Rust binary generating JS for three non-blocking conveniences.
    if agents.contains(&Agent::Claude) {
        if let Some(p) = project {
            actions.push(sync_settings(p, layers, hooks)?);
        }
    }
    Ok(actions)
}

/// The five skills, into one directory.
fn install_skills(dest_root: &Path, cx: &Cx) -> Result<Vec<Action>> {
    let mut actions = Vec::new();
    for name in SKILLS {
        let dir = skill_dir(cx.layers, cx.source, name)
            .with_context(|| format!("skill `{name}` is missing from the method tree"))?;
        let dest = dest_root.join(name);
        actions.extend(install_skill(&dir, &dest, cx.project, cx.layers)?);
    }
    Ok(actions)
}

impl SkillTarget for ClaudeCode {
    fn skills_dir(&self, cx: &Cx) -> PathBuf {
        cx.layers.claude_skills()
    }
}

/// opencode scans `~/.claude/skills` among its own global skill paths, so the
/// method is already where it looks. Naming that directory here rather than
/// writing a second copy into `~/.config/opencode/skills` is the whole point:
/// two copies of one SKILL.md is exactly the drift this design exists to stop.
///
/// If a future opencode stops reading it, this is the line to change — and
/// `bevel doctor` prints the resolved directory so the failure is visible
/// rather than silent.
impl SkillTarget for OpenCode {
    fn skills_dir(&self, cx: &Cx) -> PathBuf {
        cx.layers.claude_skills()
    }
}

impl SubagentTarget for ClaudeCode {
    fn subagents_dir(&self, cx: &Cx) -> PathBuf {
        cx.layers.claude_agents()
    }

    fn subagents(&self, cx: &Cx) -> Result<Vec<Action>> {
        let mut actions = Vec::new();
        for name in AGENT_DEFS {
            let body = agent_body(cx.layers, cx.source, name)
                .with_context(|| format!("subagent `{name}` is missing from the method tree"))?;
            let dest = self.subagents_dir(cx).join(format!("{name}.md"));
            actions.push(write_generated(&dest, &body, cx.project, cx.layers)?);
        }
        Ok(actions)
    }
}

impl SubagentTarget for OpenCode {
    fn subagents_dir(&self, cx: &Cx) -> PathBuf {
        cx.layers.opencode_agents()
    }

    fn subagents(&self, cx: &Cx) -> Result<Vec<Action>> {
        let mut actions = Vec::new();
        for name in AGENT_DEFS {
            let body = agent_body(cx.layers, cx.source, name)
                .with_context(|| format!("subagent `{name}` is missing from the method tree"))?;
            let rendered = render_subagent_for_opencode(&body)
                .with_context(|| format!("cannot render subagent `{name}` for opencode"))?;
            let dest = self.subagents_dir(cx).join(format!("{name}.md"));
            actions.push(write_generated(&dest, &rendered, cx.project, cx.layers)?);
        }
        Ok(actions)
    }
}

/// A skill's directory: user layer first, then the method tree.
///
/// Resolution is by directory rather than by file, and the whole directory is
/// taken from one layer or the other. Merging them would let a user override
/// SKILL.md and silently keep scripts the new instructions no longer match.
pub fn skill_dir(layers: &Layers, source: &Source, name: &str) -> Option<PathBuf> {
    [
        layers.user_method().join("skills").join(name),
        source.method_dir().join("skills").join(name),
    ]
    .into_iter()
    .find(|d| d.join("SKILL.md").is_file())
}

/// A skill body: user layer first, then the method tree.
pub fn skill_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    std::fs::read_to_string(skill_dir(layers, source, name)?.join("SKILL.md")).ok()
}

pub fn agent_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    read_first(&[
        layers
            .user_method()
            .join("agents")
            .join(format!("{name}.md")),
        source
            .method_dir()
            .join("agents")
            .join(format!("{name}.md")),
    ])
}

/// Either kind, for `bevel method <name>` — which is how the instructions get
/// read without a copy existing in anyone's own prompt format.
pub fn method_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    skill_body(layers, source, name).or_else(|| agent_body(layers, source, name))
}

pub fn method_names() -> Vec<&'static str> {
    SKILLS.iter().chain(AGENT_DEFS.iter()).copied().collect()
}

fn read_first(paths: &[PathBuf]) -> Option<String> {
    paths.iter().find_map(|p| std::fs::read_to_string(p).ok())
}

// ------------------------------------------------------------------ writing

/// Paths as the user recognises them: relative inside the project, `~`-prefixed
/// outside it. Sync now writes to both, and an absolute path in the middle of
/// the output reads like a mistake even when it is not.
fn display(project: Option<&Project>, layers: &Layers, path: &Path) -> String {
    if let Some(rel) = project.and_then(|p| path.strip_prefix(&p.root).ok()) {
        return rel.display().to_string();
    }
    match path.strip_prefix(&layers.home) {
        Ok(rel) => format!("~/{}", rel.display()),
        Err(_) => path.display().to_string(),
    }
}

/// Install one skill: its instructions, plus whatever else it ships.
///
/// A skill was a single markdown file for as long as every skill was one, and
/// most still are — for those this copies exactly one file and behaves as it
/// always did. `skill-creator` is the exception that makes the rule wrong:
/// its SKILL.md drives scripts and reference documents that must be on disk
/// beside it, so installing the markdown alone yields a skill that loads and
/// then fails at its first tool call.
///
/// SKILL.md keeps the generated-file treatment, since it is the one file a user
/// might reasonably want to own. Everything else is copied byte for byte: the
/// marker is an HTML comment, and appending it would break a Python script and
/// misrepresent a vendored licence.
fn install_skill(
    src: &Path,
    dest: &Path,
    project: Option<&Project>,
    layers: &Layers,
) -> Result<Vec<Action>> {
    let skill_md = src.join("SKILL.md");
    let body = std::fs::read_to_string(&skill_md)
        .with_context(|| format!("cannot read {}", skill_md.display()))?;
    let mut actions = vec![write_generated(
        &dest.join("SKILL.md"),
        &body,
        project,
        layers,
    )?];

    let mut extras = Vec::new();
    collect_files(src, src, &mut extras);
    // Sorted so `bevel sync` reports the same order every run.
    extras.sort();
    for rel in extras {
        if rel == Path::new("SKILL.md") {
            continue;
        }
        actions.push(copy_verbatim(
            &src.join(&rel),
            &dest.join(&rel),
            project,
            layers,
        )?);
    }

    actions.extend(prune_skill(src, dest, project, layers)?);
    Ok(actions)
}

/// Remove what a skill used to ship and no longer does.
///
/// Without this an upgrade only ever adds: a script dropped upstream stays on
/// disk forever, and the model finds a tool its instructions no longer mention.
///
/// Scoped hard, because `~/.claude/skills` is also where a user keeps skills of
/// their own. This only ever descends into the directory of a skill we just
/// installed, and it never removes a skill directory itself — dropping a name
/// from `SKILLS` leaves its directory behind, which is the safe way to be wrong.
fn prune_skill(
    src: &Path,
    dest: &Path,
    project: Option<&Project>,
    layers: &Layers,
) -> Result<Vec<Action>> {
    let mut actions = Vec::new();
    if !dest.is_dir() {
        return Ok(actions);
    }

    let mut installed = Vec::new();
    collect_files(dest, dest, &mut installed);
    installed.sort();
    for rel in installed {
        // Bytecode caches appear when the skill's own scripts run. They were
        // never ours to install, and deleting them every sync would be churn.
        if rel.components().any(|c| c.as_os_str() == "__pycache__") {
            continue;
        }
        if src.join(&rel).is_file() {
            continue;
        }
        let path = dest.join(&rel);
        std::fs::remove_file(&path).with_context(|| format!("cannot remove {}", path.display()))?;
        actions.push(Action::Removed(display(project, layers, &path)));
    }

    prune_empty_dirs(dest);
    Ok(actions)
}

/// Directories a prune emptied. Depth first, and never the root it was given:
/// `remove_dir` refuses anything non-empty, which is exactly the test wanted.
fn prune_empty_dirs(root: &Path) {
    let Ok(entries) = std::fs::read_dir(root) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            prune_empty_dirs(&p);
            let _ = std::fs::remove_dir(&p);
        }
    }
}

fn collect_files(dir: &Path, root: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect_files(&p, root, out);
        } else if let Ok(rel) = p.strip_prefix(root) {
            out.push(rel.to_path_buf());
        }
    }
}

/// Copy a file a skill ships beside its instructions, unchanged.
///
/// Overwritten when it differs rather than skipped as hand-edited, which is the
/// opposite of how SKILL.md is treated. These are the skill's own assets, some
/// of them third-party, and a local edit that quietly survives an update is how
/// a vendored tree rots into something nobody can reason about. The supported
/// override is the user method layer, which replaces the skill directory whole.
fn copy_verbatim(
    src: &Path,
    dest: &Path,
    project: Option<&Project>,
    layers: &Layers,
) -> Result<Action> {
    let rel = display(project, layers, dest);
    let bytes = std::fs::read(src).with_context(|| format!("cannot read {}", src.display()))?;
    if std::fs::read(dest).is_ok_and(|existing| existing == bytes) {
        return Ok(Action::Skipped(rel, "unchanged"));
    }
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(dest, &bytes).with_context(|| format!("cannot write {}", dest.display()))?;
    Ok(Action::Wrote(rel))
}

/// Write a file this tool owns, refusing to clobber anything hand-edited.
fn write_generated(
    path: &Path,
    body: &str,
    project: Option<&Project>,
    layers: &Layers,
) -> Result<Action> {
    let rel = display(project, layers, path);
    if let Ok(existing) = std::fs::read_to_string(path) {
        if !existing.contains(MARKER) {
            return Ok(Action::Skipped(rel, "hand-edited"));
        }
        if existing.trim_end().ends_with(MARKER) && existing.starts_with(body.trim_end()) {
            return Ok(Action::Skipped(rel, "unchanged"));
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    // The marker goes last: these files must open with their frontmatter fence.
    std::fs::write(path, format!("{}\n\n{MARKER}\n", body.trim_end()))
        .with_context(|| format!("cannot write {}", path.display()))?;
    Ok(Action::Wrote(rel))
}

// --------------------------------------------------- opencode frontmatter

/// What our subagent definitions declare.
#[derive(serde::Deserialize)]
struct MethodFront {
    description: String,
    /// A comma-separated scalar in every method file, not a YAML list.
    #[serde(default)]
    tools: Option<String>,
}

/// What opencode v2 reads. `name` is absent because opencode takes the id from
/// the filename, and `model` because `opus` and `fable` are Claude Code
/// shorthands rather than the `provider/model-id` opencode resolves — a
/// translated guess would pin someone else's model choice, and a literal copy
/// would name a model that does not exist.
#[derive(serde::Serialize)]
struct OpencodeFront {
    description: String,
    mode: &'static str,
    /// Absent when the source declared no `tools:` at all.
    ///
    /// An omitted `tools:` means "inherit everything" where these files come
    /// from, so emitting a closed allow-list for it would silently strip a
    /// subagent of every capability — the same unannounced narrowing that
    /// makes an unmapped tool name a hard error below. Omitting the key hands
    /// the decision back to opencode's own default.
    #[serde(skip_serializing_if = "Option::is_none")]
    permissions: Option<Vec<Permission>>,
}

#[derive(serde::Serialize)]
struct Permission {
    action: String,
    resource: &'static str,
    effect: &'static str,
}

/// serde_yaml 0.9 emits no comments, so the version note is spliced in by hand
/// the way `Spec::save` builds its own fence.
const OPENCODE_V2_NOTE: &str = "# generated by bevel — requires opencode v2 or newer";

fn render_subagent_for_opencode(body: &str) -> Result<String> {
    let (yaml, markdown) = crate::spec::split_frontmatter(body)?;
    let front: MethodFront = serde_yaml::from_str(yaml)?;
    let rendered = serde_yaml::to_string(&OpencodeFront {
        description: front.description,
        mode: "subagent",
        permissions: permissions_for(front.tools.as_deref())?,
    })?;
    Ok(format!(
        "---\n{OPENCODE_V2_NOTE}\n{rendered}---\n{markdown}"
    ))
}

/// An allow-list closed by a terminal deny, never a permissive default with
/// exceptions bolted on.
///
/// The two differ precisely on the property the subagents exist for: a
/// reviewer that gained a tool nobody granted is the failure. Only the closed
/// form makes that impossible, and the order matters because opencode resolves
/// by last match.
fn permissions_for(tools: Option<&str>) -> Result<Option<Vec<Permission>>> {
    let Some(tools) = tools else {
        return Ok(None);
    };
    let mut out = Vec::new();
    for tool in tools.split(',') {
        let tool = tool.trim();
        if tool.is_empty() {
            continue;
        }
        let (action, resource) = opencode_action(tool)?;
        out.push(Permission {
            action: action.into(),
            resource,
            effect: "allow",
        });
    }
    if out.is_empty() {
        return Ok(None);
    }
    out.push(Permission {
        action: "*".into(),
        resource: "*",
        effect: "deny",
    });
    Ok(Some(out))
}

/// Our tool names, in opencode's vocabulary.
///
/// An unrecognised tool is an error rather than a silently dropped line. The
/// quiet alternative would narrow a subagent's capabilities without saying so,
/// which is indistinguishable from the translation working — and `sync` is a
/// command run deliberately, so a loud failure here is one someone can fix.
fn opencode_action(tool: &str) -> Result<(&'static str, &'static str)> {
    Ok(match tool {
        "Read" => ("read", "**"),
        "Grep" => ("grep", "**"),
        "Glob" => ("glob", "**"),
        // opencode gates its `write` tool behind the `edit` permission, so
        // granting `edit` is what actually makes writing possible.
        "Write" | "Edit" => ("edit", "**"),
        "WebFetch" => ("webfetch", "*"),
        "Bash" => ("bash", "*"),
        other => bail!(
            "no opencode equivalent for tool `{other}`\n  \
             add one to `opencode_action` rather than letting the subagent \
             quietly lose the capability"
        ),
    })
}

/// Add the deny rule and, optionally, the hooks — without disturbing anything
/// else in the file.
///
/// A merge rather than a write: this file is the user's, and clobbering their
/// permissions to install one rule would be a bad trade.
fn sync_settings(project: &Project, layers: &Layers, hooks: bool) -> Result<Action> {
    let path = project.root.join(".claude/settings.json");
    let rel = display(Some(project), layers, &path);

    let mut root: Value = match std::fs::read_to_string(&path) {
        Ok(text) if !text.trim().is_empty() => serde_json::from_str(&text)
            .with_context(|| format!("cannot parse {}", path.display()))?,
        _ => Value::Object(Map::new()),
    };
    let before = root.clone();

    {
        let obj = root
            .as_object_mut()
            .context("settings.json must contain a JSON object")?;
        let permissions = obj
            .entry("permissions")
            .or_insert_with(|| json!({}))
            .as_object_mut()
            .context("permissions must be a JSON object")?;
        let deny = permissions
            .entry("deny")
            .or_insert_with(|| json!([]))
            .as_array_mut()
            .context("permissions.deny must be an array")?;
        deny.retain(|v| v.as_str() != Some(LEGACY_DENY_RULE));
        if !deny.iter().any(|v| v.as_str() == Some(DENY_RULE)) {
            deny.push(json!(DENY_RULE));
        }
    }

    if hooks {
        install_hooks(&mut root)?;
    }

    if root == before {
        return Ok(Action::Skipped(rel, "up to date"));
    }
    std::fs::create_dir_all(path.parent().unwrap())?;
    std::fs::write(&path, format!("{}\n", serde_json::to_string_pretty(&root)?))?;
    Ok(Action::Wrote(rel))
}

/// Three hooks, all of them cheap and none of them blocking.
///
/// Deliberately absent: anything that refuses a write outside `specs/`. It is
/// tempting, but it would break ordinary coding done outside the pipeline, and
/// that is exactly the kind of harness assumption worth not making.
fn install_hooks(root: &mut Value) -> Result<()> {
    let ours = [
        (
            "PostToolUse",
            Some("Edit|Write|MultiEdit"),
            // Reads the hook payload from stdin, so no `jq` is required.
            "bevel fmt --hook",
        ),
        ("SessionStart", None, "bevel status --brief"),
        // Advisory only. A blocking Stop hook can trap an agent in a loop.
        ("Stop", None, "bevel pending"),
    ];

    let obj = root
        .as_object_mut()
        .context("settings.json is not an object")?;
    let hooks = obj
        .entry("hooks")
        .or_insert_with(|| json!({}))
        .as_object_mut()
        .context("hooks must be a JSON object")?;

    for (event, matcher, command) in ours {
        let list = hooks
            .entry(event)
            .or_insert_with(|| json!([]))
            .as_array_mut()
            .with_context(|| format!("hooks.{event} must be an array"))?;

        // Drop any entry we previously installed, so sync stays idempotent
        // without touching hooks the user added themselves.
        list.retain(|entry| !is_ours(entry));

        let mut group = Map::new();
        if let Some(m) = matcher {
            group.insert("matcher".into(), json!(m));
        }
        group.insert(
            "hooks".into(),
            json!([{ "type": "command", "command": command }]),
        );
        list.push(Value::Object(group));
    }
    Ok(())
}

fn is_ours(entry: &Value) -> bool {
    entry
        .get("hooks")
        .and_then(Value::as_array)
        .map(|hs| {
            hs.iter().any(|h| {
                h.get("command")
                    .and_then(Value::as_str)
                    .map(|c| COMMAND_PREFIXES.iter().any(|p| c.starts_with(p)))
                    .unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

/// The two-line `CLAUDE.md` that points at the notes.
///
/// Claude Code loads `CLAUDE.md` every turn and opencode reads `AGENTS.md`
/// first, so the body belongs in the file both can reach and this one points at
/// it. A pointer cannot drift from what it points at; a second copy can.
///
/// Printed by `bevel notes claude`, never written. See [`notes`].
const CLAUDE_MD_POINTER: &str = r#"See [AGENTS.md](AGENTS.md).

One instruction lives in one place; this file is a pointer so the two
cannot drift apart.
"#;

/// What a project needs said about itself. The pipeline is here rather than in
/// the skills because it is the part a reader needs before invoking one.
///
/// **The two skills are the entry points, and the commands are shown nested
/// under the one that runs them.** A flat list of commands reads as a sequence
/// to type, which is wrong twice over: `/shape` already runs `bevel shape`,
/// `validate` and `review` itself, `/implement` already runs `start`, `verify`
/// and `close`, and an agent working the list by hand skips every instruction
/// in between — the interview, the blind spot pass, the adversarial review.
/// The nesting is what makes the skill, not the command, the thing you invoke.
///
/// Loaded every turn, so it is kept under 50 lines and `bevel doctor` says so
/// when it is not. That budget is why the list stops where it does: `fmt`,
/// `index`, `board`, `list` and `migrate` are discoverable from `bevel --help`
/// and cost nothing to omit, while a command an agent needs mid-loop and cannot
/// guess earns its line.
///
/// Printed by `bevel notes`, never written. Editing it therefore changes what
/// the next reader is *offered*, and nothing already on anyone's disk — which
/// is what makes it freely editable. It carries no generated marker for the
/// same reason: the moment a user pastes this into their repository it is
/// theirs, and a marker claiming otherwise would be false the second it landed.
const AGENTS_MD: &str = r#"# Agent notes

Non-obvious things only. Anything derivable from the file tree does not belong
here, and nothing here is repeated in another file.

## The loop

Ideas live in `INBOX.md`. Shaping turns one into a spec under `specs/`; a human
approves it; implementation builds it against that spec. Two skills drive it,
and each runs the commands indented under it — invoke the skill, not the list:

```
bevel status                    where things stand — start here
bevel inbox add "<idea>"        capture it; precision comes later

/shape <n>                      inbox item -> a spec a human can approve
  bevel shape <n>               reserve an id, scaffold specs/NNNN-slug/
  bevel validate <id>           deterministic rules; draft -> review
  bevel review <id>             the dossier the human approves from

/implement <id>                 an approved spec -> code
  bevel start <id>              claim it; checks the gate first
  bevel docs <lib> --spec <id>  version-pinned docs from the lockfile
  bevel verify --affected       only what changed, plus its dependents
  bevel close <id>              markers, verification, then done
```

`bevel approve <id>` belongs between the two and is absent on purpose: it
requires a terminal, so an agent cannot run it. Ask the human, and say what
changed. `bevel pause <id>` hands the slot back without losing the approval.

Without slash commands, `bevel method show shape` and `bevel method show
implement` print the same text the skills load.

## Gotchas

<!-- Conventions and traps a competent newcomer to this repo would get wrong.
     Not a tutorial, and not anything the file tree already says.
     Keep this file under 50 lines. -->

`bevel review`, `board`, `doctor --context --html` and `index --html` write
HTML into `.bevel/cache/`. **Never read one back.** They exist for a human's
eyes; a page costs several times the tokens of the markdown behind it, and
every fact in one is available to you from `--json` or the source file. Point
the user at the path and move on.
"#;

/// Which file `bevel notes` is printing the markdown for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Notes {
    /// The body: what a project says about itself, for `AGENTS.md`.
    Agents,
    /// The pointer at it, for `CLAUDE.md`.
    Claude,
}

/// The markdown for one of the two instruction files, to print.
///
/// A suggestion rather than an installation, and the whole of bevel's part in
/// it. What a repository says about itself is the user's writing — the seed is
/// only a good first draft of it — so bevel offers the text on stdout and stops
/// there. `bevel notes > AGENTS.md` is one keystroke; a sync that decides on
/// its own when to write, skip, move or preserve that file is a standing risk
/// to prose nobody else can reconstruct.
pub fn notes(which: Notes) -> &'static str {
    match which {
        Notes::Agents => AGENTS_MD,
        Notes::Claude => CLAUDE_MD_POINTER,
    }
}

/// Where each method file resolved from, for `doctor`. Without this, "why is my
/// edit not taking effect?" is an afternoon.
pub fn method_sources(layers: &Layers, source: &Source) -> Vec<(String, PathBuf, &'static str)> {
    let mut out = Vec::new();
    for name in SKILLS {
        let user = layers
            .user_method()
            .join("skills")
            .join(name)
            .join("SKILL.md");
        let tree = source
            .method_dir()
            .join("skills")
            .join(name)
            .join("SKILL.md");
        out.push(pick(format!("skill/{name}"), user, tree));
    }
    for name in AGENT_DEFS {
        let user = layers
            .user_method()
            .join("agents")
            .join(format!("{name}.md"));
        let tree = source
            .method_dir()
            .join("agents")
            .join(format!("{name}.md"));
        out.push(pick(format!("agent/{name}"), user, tree));
    }
    out
}

/// Where each resource kind lands, per agent, for `doctor`.
///
/// This exists because of the one assumption holding up the whole opencode
/// scope: that opencode reads `~/.claude/skills`. If that ever stops being
/// true, nothing fails — sync reports success, the subagents land correctly,
/// and the two skills that *are* the pipeline are simply invisible. Printing
/// the resolved directory is what turns that from silent into obvious.
pub fn destinations(layers: &Layers, agents: &[Agent]) -> Vec<(String, String, PathBuf)> {
    let mut out = Vec::new();
    for agent in agents {
        let cx = Cx {
            project: None,
            layers,
            source: &Source {
                kind: crate::method::Kind::Local,
                root: PathBuf::new(),
                origin: String::new(),
            },
        };
        let name = agent.as_str().to_string();
        out.push((
            name.clone(),
            "skills".into(),
            agent.skills().skills_dir(&cx),
        ));
        out.push((
            name,
            "subagents".into(),
            agent.subagents().subagents_dir(&cx),
        ));
    }
    out
}

fn pick(label: String, user: PathBuf, tree: PathBuf) -> (String, PathBuf, &'static str) {
    if user.is_file() {
        (label, user, "user")
    } else if tree.is_file() {
        (label, tree, "method")
    } else {
        (label, tree, "MISSING")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() -> (tempfile::TempDir, Project, Layers, Source) {
        let tmp = tempfile::tempdir().unwrap();
        crate::project::init(tmp.path(), false).unwrap();
        let project = Project::discover_from(tmp.path()).unwrap();
        let layers = Layers {
            config: tmp.path().join("cfg"),
            cache: tmp.path().join("cache"),
            // Never the real $HOME: these tests write into it.
            home: tmp.path().join("home"),
            // Nor the real `~/.config/opencode`, for the same reason — this one
            // holds agents a developer wrote themselves.
            opencode: tmp.path().join("home/.config/opencode"),
        };
        // This repository is itself a method tree, which is what ships.
        let source = Source {
            kind: crate::method::Kind::Local,
            root: std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")),
            origin: "repo".into(),
        };
        (tmp, project, layers, source)
    }

    #[test]
    fn a_full_sync_writes_everything_once_and_is_idempotent() {
        let (_t, p, l, m) = setup();
        let first = sync(Some(&p), &l, &m, &[Agent::Claude], false).unwrap();
        assert!(
            first.iter().all(|a| matches!(a, Action::Wrote(_))),
            "{first:?}"
        );
        let skill = l.claude_skills().join("shape/SKILL.md");
        assert!(skill.is_file());
        assert!(l.claude_agents().join("spec-critic.md").is_file());

        let text = std::fs::read_to_string(&skill).unwrap();
        assert!(text.starts_with("---\nname: shape"));

        let second = sync(Some(&p), &l, &m, &[Agent::Claude], false).unwrap();
        assert!(
            second.iter().all(|a| matches!(a, Action::Skipped(_, _))),
            "{second:?}"
        );
    }

    /// Claude Code reads personal skills from `~/.claude/skills` and nowhere
    /// else. A skill installed anywhere else looks installed and never loads,
    /// which is the one failure mode with no symptom.
    #[test]
    fn the_method_installs_where_claude_code_reads_it() {
        let (_t, p, l, m) = setup();
        sync(Some(&p), &l, &m, &[Agent::Claude], true).unwrap();
        assert!(l.home.join(".claude/skills/implement/SKILL.md").is_file());
        assert!(l.home.join(".claude/agents/domain-scout.md").is_file());
        // Nothing per-project, and nothing in the directory the standard
        // proposes but Claude Code does not read.
        assert!(!p.root.join(".claude/skills").exists());
        assert!(!p.root.join(".claude/agents").exists());
        assert!(!l.home.join(".agents").exists());
        // What is genuinely project-scoped stays behind. Configuration only:
        // the project's prose is printed by `bevel notes`, not installed.
        assert!(p.root.join(".claude/settings.json").is_file());
    }

    /// What lives in `$HOME` is the machine's, not a project's. Requiring a
    /// project first would be a dependency that does not exist — and it would
    /// bite on a fresh machine, where there is nothing to init yet.
    #[test]
    fn the_method_installs_with_no_project_at_all() {
        let (_t, _p, l, m) = setup();
        let actions = sync(None, &l, &m, &[Agent::Claude], true).unwrap();
        assert!(l.claude_skills().join("shape/SKILL.md").is_file());
        assert!(l.claude_agents().join("spec-critic.md").is_file());
        // Every path reported has to be one the user can find without a root
        // to be relative to.
        for a in &actions {
            let Action::Wrote(p) = a else { continue };
            assert!(p.starts_with("~/"), "{p}");
        }
    }

    /// The project half must not be invented from thin air when there is no
    /// project: there is no directory it could correctly be written to.
    #[test]
    fn without_a_project_nothing_project_scoped_is_written() {
        let (t, _p, l, m) = setup();
        sync(None, &l, &m, &[Agent::Claude], true).unwrap();
        for stray in ["CLAUDE.md", ".claude/settings.json"] {
            assert!(!l.home.join(stray).exists(), "{stray} in $HOME");
            assert!(!t.path().join(stray).exists(), "{stray} outside a project");
        }
    }

    /// AGENTS.md is loaded every turn by both agents, so what bevel offers for
    /// it carries the pipeline itself and stays inside the budget `bevel
    /// doctor` enforces — offered text that would fail the audit on arrival is
    /// a worse starting point than none.
    #[test]
    fn the_project_notes_are_printed_for_a_human_to_apply() {
        let text = notes(Notes::Agents);

        // Both skills, because they are the entry points: an agent that reads a
        // bare command list works it by hand and skips everything the skill
        // does between the commands — the interview, the blind spot pass, the
        // adversarial review. Naming `/shape` and `/implement` is what makes
        // the commands beneath them a description rather than a recipe.
        assert!(text.contains("/shape"));
        assert!(text.contains("/implement"));

        // Every command a skill runs, so the loop reads end to end and an agent
        // that has to drive it by hand still can.
        for cmd in [
            "bevel status",
            "bevel inbox add",
            "bevel shape <n>",
            "bevel validate <id>",
            "bevel review <id>",
            "bevel start <id>",
            "bevel docs <lib> --spec <id>",
            "bevel verify --affected",
            "bevel close <id>",
            "bevel pause <id>",
        ] {
            assert!(text.contains(cmd), "the loop lost `{cmd}`");
        }

        // The exact invocation, not an approximation of it: `bevel method
        // shape` is an unrecognised subcommand and exits 2, so a seed that
        // says it sends every agent down a failing path on its first read.
        assert!(text.contains("bevel method show shape"));
        // The reason approve is absent has to be stated, or an agent will try.
        assert!(text.contains("requires a terminal"));

        // The budget is the ceiling this list grows against, and the user still
        // has to fit their own gotchas underneath it (DESIGN.md §13).
        assert!(text.lines().count() <= 50, "{} lines", text.lines().count());

        // No marker. This text becomes the user's the moment they apply it, and
        // a marker saying "edit the method layer, not this file" would be false
        // on arrival — as well as inviting some future sync to clobber it.
        assert!(!text.contains(MARKER));

        // The pointer stays a pointer: if the body were duplicated there the two
        // would be free to drift, which is the whole reason for the indirection.
        let claude = notes(Notes::Claude);
        assert!(claude.contains("[AGENTS.md](AGENTS.md)"));
        assert!(!claude.contains("bevel start <id>"));
        assert!(claude.lines().count() < 10, "the pointer grew a body");
        assert!(!claude.contains(MARKER));
    }

    #[test]
    fn hooks_are_installed_only_when_asked_and_never_duplicate() {
        let (_t, p, l, m) = setup();
        sync(Some(&p), &l, &m, &[Agent::Claude], false).unwrap();
        let path = p.root.join(".claude/settings.json");
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert!(v.get("hooks").is_none());

        sync(Some(&p), &l, &m, &[Agent::Claude], true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let post = v["hooks"]["PostToolUse"].as_array().unwrap();
        assert_eq!(post.len(), 1);
        assert_eq!(post[0]["matcher"], "Edit|Write|MultiEdit");
        assert_eq!(post[0]["hooks"][0]["command"], "bevel fmt --hook");
        assert_eq!(
            v["hooks"]["SessionStart"][0]["hooks"][0]["command"],
            "bevel status --brief"
        );

        // Running twice must not stack duplicates.
        sync(Some(&p), &l, &m, &[Agent::Claude], true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(v["hooks"]["PostToolUse"].as_array().unwrap().len(), 1);
    }

    /// A rename must not leave both generations installed side by side.
    #[test]
    fn entries_from_the_previous_tool_name_are_replaced_not_duplicated() {
        let (_t, p, l, m) = setup();
        let path = p.root.join(".claude/settings.json");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            r#"{"permissions":{"deny":["Bash(harness approve*)"]},
                "hooks":{"Stop":[{"hooks":[{"type":"command","command":"harness pending"}]}]}}"#,
        )
        .unwrap();

        sync(Some(&p), &l, &m, &[Agent::Claude], true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        let deny = v["permissions"]["deny"].as_array().unwrap();
        assert_eq!(deny.len(), 1);
        assert_eq!(deny[0], DENY_RULE);

        let stop = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 1);
        assert_eq!(stop[0]["hooks"][0]["command"], "bevel pending");
    }

    #[test]
    fn a_users_own_hooks_survive_installation() {
        let (_t, p, l, m) = setup();
        let path = p.root.join(".claude/settings.json");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            r#"{"hooks":{"Stop":[{"hooks":[{"type":"command","command":"notify-send done"}]}]}}"#,
        )
        .unwrap();

        sync(Some(&p), &l, &m, &[Agent::Claude], true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let stop = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 2);
        assert!(stop
            .iter()
            .any(|e| e["hooks"][0]["command"] == "notify-send done"));
        assert!(stop
            .iter()
            .any(|e| e["hooks"][0]["command"] == "bevel pending"));
    }

    #[test]
    fn a_missing_method_tree_is_a_clear_error_not_a_panic() {
        let (_t, p, l, _m) = setup();
        let empty = Source {
            kind: crate::method::Kind::Local,
            root: _t.path().join("nowhere"),
            origin: "test".into(),
        };
        let err = sync(Some(&p), &l, &empty, &[Agent::Claude], false)
            .unwrap_err()
            .to_string();
        assert!(err.contains("not available"), "{err}");
    }

    #[test]
    fn method_bodies_are_printable_and_the_user_layer_wins() {
        let (_t, _p, l, m) = setup();
        assert!(method_body(&l, &m, "shape")
            .unwrap()
            .contains("name: shape"));
        assert!(method_body(&l, &m, "spec-critic")
            .unwrap()
            .contains("name: spec-critic"));
        assert!(method_body(&l, &m, "nope").is_none());
        assert_eq!(method_names().len(), 12);

        let src = l.user_method().join("skills/shape/SKILL.md");
        std::fs::create_dir_all(src.parent().unwrap()).unwrap();
        std::fs::write(&src, "custom shape\n").unwrap();
        assert_eq!(method_body(&l, &m, "shape").unwrap(), "custom shape\n");
    }

    /// A multi-file skill has to arrive whole. `skill-creator` calls scripts and
    /// reference documents out of its SKILL.md, so the markdown on its own is a
    /// skill that loads and then fails at its first tool call — and the licence
    /// of a vendored skill has to travel with it to where it was installed.
    #[test]
    fn a_multi_file_skill_installs_its_whole_tree() {
        let (_t, _p, l, m) = setup();
        sync(None, &l, &m, &[Agent::Claude], false).unwrap();

        let dir = l.claude_skills().join("skill-creator");
        for rel in [
            "SKILL.md",
            "scripts/run_eval.py",
            "references/schemas.md",
            "agents/grader.md",
            "LICENSE.txt",
        ] {
            assert!(dir.join(rel).is_file(), "{rel} was not installed");
        }

        // Byte for byte: the marker is an HTML comment, which would break the
        // script and tamper with the licence.
        let src = m.method_dir().join("skills/skill-creator");
        for rel in ["scripts/run_eval.py", "LICENSE.txt"] {
            assert_eq!(
                std::fs::read(src.join(rel)).unwrap(),
                std::fs::read(dir.join(rel)).unwrap(),
                "{rel} was not copied verbatim"
            );
        }

        // The obligation the copy exists to meet.
        let licence = std::fs::read_to_string(dir.join("LICENSE.txt")).unwrap();
        assert!(licence.contains("Apache License"));
        assert!(licence.contains("Copyright 2026 Anthropic, PBC."));
    }

    /// Without a prune an upgrade only ever adds, and a script dropped upstream
    /// stays on disk for the model to find.
    #[test]
    fn a_file_a_skill_no_longer_ships_is_removed() {
        let (_t, _p, l, m) = setup();
        sync(None, &l, &m, &[Agent::Claude], false).unwrap();

        let dir = l.claude_skills().join("skill-creator");
        let stale = dir.join("scripts/dropped_upstream.py");
        std::fs::write(&stale, "gone\n").unwrap();
        let nested = dir.join("old/deeper/note.md");
        std::fs::create_dir_all(nested.parent().unwrap()).unwrap();
        std::fs::write(&nested, "gone\n").unwrap();

        let actions = sync(None, &l, &m, &[Agent::Claude], false).unwrap();
        assert!(!stale.exists());
        assert!(!nested.exists());
        assert!(!dir.join("old").exists(), "emptied directories go too");
        // What the skill does still ship is untouched.
        assert!(dir.join("scripts/run_eval.py").is_file());
        assert!(dir.join("LICENSE.txt").is_file());
        assert!(actions
            .iter()
            .any(|a| matches!(a, Action::Removed(p) if p.ends_with("dropped_upstream.py"))));
    }

    /// `~/.claude/skills` is the user's directory too. A prune that wandered out
    /// of the skill it was installing would delete someone else's work, so this
    /// is the test that matters most about it.
    #[test]
    fn pruning_stays_inside_the_skill_it_installed() {
        let (_t, _p, l, m) = setup();
        let mine = l.claude_skills().join("my-own/SKILL.md");
        std::fs::create_dir_all(mine.parent().unwrap()).unwrap();
        std::fs::write(&mine, "---\nname: my-own\n---\nmine\n").unwrap();
        let deep = l.claude_skills().join("my-own/scripts/thing.py");
        std::fs::create_dir_all(deep.parent().unwrap()).unwrap();
        std::fs::write(&deep, "mine\n").unwrap();

        sync(None, &l, &m, &[Agent::Claude], false).unwrap();
        assert!(mine.is_file(), "a personal skill was pruned");
        assert!(deep.is_file(), "a personal skill was pruned");
    }

    /// Bytecode caches are created by running the skill, not by installing it.
    #[test]
    fn a_bytecode_cache_the_skill_created_survives() {
        let (_t, _p, l, m) = setup();
        sync(None, &l, &m, &[Agent::Claude], false).unwrap();
        let cache = l
            .claude_skills()
            .join("skill-creator/scripts/__pycache__/utils.cpython-312.pyc");
        std::fs::create_dir_all(cache.parent().unwrap()).unwrap();
        std::fs::write(&cache, "bytecode").unwrap();

        sync(None, &l, &m, &[Agent::Claude], false).unwrap();
        assert!(cache.is_file());
    }

    /// The single-file skills predate directories and must be unaffected: one
    /// file in, one file out, with nothing invented alongside it.
    #[test]
    fn a_single_file_skill_still_installs_as_one_file() {
        let (_t, _p, l, m) = setup();
        sync(None, &l, &m, &[Agent::Claude], false).unwrap();
        let dir = l.claude_skills().join("shape");
        let files: Vec<_> = std::fs::read_dir(&dir)
            .unwrap()
            .flatten()
            .map(|e| e.file_name())
            .collect();
        assert_eq!(files, ["SKILL.md"], "{files:?}");
    }

    #[test]
    fn a_hand_edited_generated_file_is_never_clobbered() {
        let (_t, p, l, m) = setup();
        let dest = l.claude_skills().join("shape/SKILL.md");
        std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
        std::fs::write(&dest, "---\nname: shape\n---\nmine\n").unwrap();

        sync(Some(&p), &l, &m, &[Agent::Claude], false).unwrap();
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\nname: shape\n---\nmine\n"
        );
    }

    // ------------------------------------------------ acceptance, spec 0001

    /// The failure mode with no symptom: a file installed where nothing reads
    /// it looks exactly like a file installed correctly. opencode scans
    /// `~/.config/opencode/agents/<name>.md` — plural, and with no
    /// `.claude/agents` fallback — so all seven definitions must land there,
    /// named for the agent.
    #[test]
    fn opencode_subagents_land_where_opencode_reads_them() {
        let (_t, p, l, m) = setup();
        sync(Some(&p), &l, &m, &[Agent::Opencode], false).unwrap();

        for name in AGENT_DEFS {
            let dest = l.opencode_agents().join(format!("{name}.md"));
            assert!(dest.is_file(), "{name} was not installed for opencode");
        }
        // Plural, and never Claude Code's directory: opencode has no
        // `.claude/agents` fallback, so a file there is a file it never reads.
        assert!(l.home.join(".config/opencode/agents").is_dir());
        assert!(!l.home.join(".config/opencode/agent").exists());
        assert!(!l.claude_agents().exists());
    }

    /// The property the subagents exist for, and it is not "read-only": the
    /// seven carry four different tool sets. `mockup-builder` writes and does
    /// not search; `context-packer` writes and fetches. A subagent must come
    /// out the far side with the tools it declared and nothing more — the
    /// `permissions` allow-list closed by a terminal deny, so a tool nobody
    /// granted cannot appear.
    #[test]
    fn a_subagents_tool_set_survives_translation_into_opencode_permissions() {
        let (_t, p, l, m) = setup();
        sync(Some(&p), &l, &m, &[Agent::Opencode], false).unwrap();

        let read = |name: &str| {
            let text =
                std::fs::read_to_string(l.opencode_agents().join(format!("{name}.md"))).unwrap();
            let (yaml, _) = crate::spec::split_frontmatter(&text).unwrap();
            serde_yaml::from_str::<serde_yaml::Value>(yaml).unwrap()
        };
        let actions = |v: &serde_yaml::Value, effect: &str| -> Vec<String> {
            v["permissions"]
                .as_sequence()
                .unwrap()
                .iter()
                .filter(|p| p["effect"].as_str() == Some(effect))
                .map(|p| p["action"].as_str().unwrap().to_string())
                .collect()
        };

        // A searcher that may shell out, and must not write.
        let scout = read("domain-scout");
        assert_eq!(scout["mode"].as_str(), Some("subagent"));
        assert_eq!(actions(&scout, "allow"), ["read", "grep", "glob", "bash"]);

        // The two that legitimately write would be corrupted by a blanket
        // "read-only" translation, which is why this is not that.
        let mockup = read("mockup-builder");
        assert_eq!(actions(&mockup, "allow"), ["read", "edit"]);
        let packer = read("context-packer");
        assert!(actions(&packer, "allow").contains(&"webfetch".to_string()));

        // Closed by a terminal deny, and last, because opencode resolves by
        // last match: a tool nobody granted must be impossible, not merely
        // unmentioned.
        for v in [&scout, &mockup, &packer] {
            let perms = v["permissions"].as_sequence().unwrap();
            let last = perms.last().unwrap();
            assert_eq!(last["action"].as_str(), Some("*"));
            assert_eq!(last["effect"].as_str(), Some("deny"));
            assert_eq!(actions(v, "deny"), ["*"]);
        }

        // The version the permissions shape belongs to, stated in the file.
        let text = std::fs::read_to_string(l.opencode_agents().join("domain-scout.md")).unwrap();
        assert!(text.contains("requires opencode v2 or newer"));

        // An unrecognised tool must stop the run rather than quietly narrow a
        // subagent to the tools we happened to recognise.
        assert!(permissions_for(Some("Read, Telepathy")).is_err());

        // And an omitted `tools:` means "inherit everything" where these files
        // come from, so a closed allow-list would strip the subagent of every
        // capability — the same silent narrowing, arrived at by doing nothing.
        assert!(permissions_for(None).unwrap().is_none());
    }

    /// `model: opus` and `model: fable` are Claude Code shorthands. opencode
    /// wants `provider/model-id` and would fail to resolve a model literally
    /// called "opus", so the field is dropped rather than transliterated —
    /// letting opencode apply its own default instead of a broken pin.
    #[test]
    fn the_claude_only_model_shorthand_is_dropped_rather_than_translated() {
        let (_t, p, l, m) = setup();
        sync(Some(&p), &l, &m, &[Agent::Opencode], false).unwrap();

        // The method files really do carry the shorthands, or this proves
        // nothing at all.
        let source =
            std::fs::read_to_string(m.method_dir().join("agents/domain-scout.md")).unwrap();
        assert!(source.contains("model: opus") || source.contains("model: fable"));

        for name in AGENT_DEFS {
            let text =
                std::fs::read_to_string(l.opencode_agents().join(format!("{name}.md"))).unwrap();
            let (yaml, _) = crate::spec::split_frontmatter(&text).unwrap();
            let front: serde_yaml::Value = serde_yaml::from_str(yaml).unwrap();
            assert!(
                front["model"].is_null(),
                "{name} carried a model into opencode"
            );
            // `name` goes too: opencode takes the id from the filename, and a
            // stale one here would disagree with the file it sits in.
            assert!(front["name"].is_null(), "{name} carried a redundant name");
            assert!(
                !front["description"].is_null(),
                "{name} lost its description"
            );
        }
    }

    /// The invariant that replaced an entire migration, three of its helpers
    /// and every test they needed: **sync does not touch these two files.**
    ///
    /// What is gone with them is the point. There is no byte comparison against
    /// a frozen copy of what shipped, because nothing needs classifying. There
    /// is no relocation of a user's own writing, because nothing is in the way.
    /// There is no symlink check, because nothing is written through anything.
    /// A file that cannot be decoded as UTF-8 needs no special case, because it
    /// is never read. Each of those was a correct answer to a question this
    /// design stopped asking.
    #[test]
    fn sync_never_writes_or_moves_the_projects_instruction_files() {
        // Nothing where there was nothing, for either agent or both.
        let (_t, p, l, m) = setup();
        let actions = sync(Some(&p), &l, &m, &[Agent::Claude, Agent::Opencode], false).unwrap();
        assert!(!p.root.join("AGENTS.md").exists());
        assert!(!p.root.join("CLAUDE.md").exists());
        assert!(
            !actions
                .iter()
                .any(|a| format!("{a}").contains("AGENTS.md")
                    || format!("{a}").contains("CLAUDE.md")),
            "{actions:?}"
        );

        // And nothing to what is already there — whoever wrote it, and whether
        // it is the user's prose, bevel's own seed applied by hand, or bytes no
        // decoder will accept.
        let (_t2, p2, l2, m2) = setup();
        let mine = "# My notes\n\nDeploy with `make ship`. Never force-push main.\n";
        let latin1 = b"# nai\xefve notes\n";
        std::fs::write(p2.root.join("AGENTS.md"), mine).unwrap();
        std::fs::write(p2.root.join("CLAUDE.md"), latin1).unwrap();

        sync(
            Some(&p2),
            &l2,
            &m2,
            &[Agent::Claude, Agent::Opencode],
            false,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(p2.root.join("AGENTS.md")).unwrap(),
            mine
        );
        assert_eq!(std::fs::read(p2.root.join("CLAUDE.md")).unwrap(), latin1);

        // Applying the seed verbatim does not make it bevel's again. This is the
        // case the old byte comparison existed to catch, and the one that made
        // the seed unimprovable: it is now indistinguishable from any other
        // file the user put there, which is exactly right.
        let (_t3, p3, l3, m3) = setup();
        std::fs::write(p3.root.join("AGENTS.md"), notes(Notes::Agents)).unwrap();
        sync(Some(&p3), &l3, &m3, &[Agent::Claude], false).unwrap();
        assert_eq!(
            std::fs::read_to_string(p3.root.join("AGENTS.md")).unwrap(),
            notes(Notes::Agents)
        );
    }

    /// Detection and parsing are the two behaviours every other test bypasses
    /// by passing its agents explicitly.
    #[test]
    fn agents_are_detected_additively_and_an_unknown_name_is_refused() {
        let (_t, _p, l, _m) = setup();
        // Nothing installed yet: rendering for nobody would be a silent no-op
        // on a fresh machine, so Claude Code is the floor.
        assert_eq!(detect(&l), vec![Agent::Claude]);

        std::fs::create_dir_all(l.opencode_home()).unwrap();
        assert_eq!(detect(&l), vec![Agent::Opencode]);
        std::fs::create_dir_all(l.claude_home()).unwrap();
        assert_eq!(detect(&l), vec![Agent::Claude, Agent::Opencode]);

        assert_eq!(Agent::parse("opencode").unwrap(), Agent::Opencode);
        assert_eq!(Agent::parse(" Claude ").unwrap(), Agent::Claude);
        // The mistake the deleted code made: accepting a name and rendering
        // nothing for it, which reads exactly like success.
        let err = Agent::parse("cursor").unwrap_err().to_string();
        assert!(err.contains("unknown agent"), "{err}");
        assert!(err.contains("claude, opencode"), "{err}");
    }

    /// `~/.config/opencode` holds agents the user wrote themselves, exactly as
    /// `~/.claude/skills` does. The prune must stay inside what this sync
    /// installed and must never cross from one agent's tree into another's.
    #[test]
    fn pruning_for_one_agent_never_reaches_another_agents_directory() {
        let (_t, p, l, m) = setup();

        // Agents the user wrote themselves, in both trees.
        let theirs_oc = l.opencode_agents().join("my-reviewer.md");
        std::fs::create_dir_all(theirs_oc.parent().unwrap()).unwrap();
        std::fs::write(&theirs_oc, "---\ndescription: mine\n---\nmine\n").unwrap();
        let theirs_cc = l.claude_agents().join("my-reviewer.md");
        std::fs::create_dir_all(theirs_cc.parent().unwrap()).unwrap();
        std::fs::write(&theirs_cc, "---\nname: mine\n---\nmine\n").unwrap();

        sync(Some(&p), &l, &m, &[Agent::Claude, Agent::Opencode], false).unwrap();
        assert!(theirs_oc.is_file(), "a personal opencode agent was pruned");
        assert!(theirs_cc.is_file(), "a personal Claude agent was pruned");

        // Rendering for one agent must not reach into the other's tree, in
        // either direction.
        let (_t2, p2, l2, m2) = setup();
        sync(Some(&p2), &l2, &m2, &[Agent::Opencode], false).unwrap();
        assert!(!l2.claude_agents().exists());
        let (_t3, p3, l3, m3) = setup();
        sync(Some(&p3), &l3, &m3, &[Agent::Claude], false).unwrap();
        assert!(!l3.opencode_home().exists());
    }

    /// Idempotence, across two renderers — asserting the *reason*, not just the
    /// absence of writes. "Nothing changed" is also what a sync reports when it
    /// skips everything as hand-edited, which is the migration bug this spec
    /// exists to fix; only `unchanged` distinguishes success from that failure.
    #[test]
    fn a_second_sync_for_both_agents_skips_everything_as_unchanged() {
        let (_t, p, l, m) = setup();
        let both = [Agent::Claude, Agent::Opencode];

        let first = sync(Some(&p), &l, &m, &both, true).unwrap();
        assert!(first.iter().any(|a| matches!(a, Action::Wrote(_))));

        let second = sync(Some(&p), &l, &m, &both, true).unwrap();
        // The reason matters more than the absence of writes. "Nothing changed"
        // is also what a sync reports when it skips everything as hand-edited,
        // which is the migration bug this criterion exists to catch — so a
        // green here must mean the files match, not that they were untouchable.
        for action in &second {
            match action {
                Action::Skipped(path, why) => assert!(
                    *why == "unchanged" || *why == "up to date",
                    "{path} skipped as {why}"
                ),
                other => panic!("second sync was not idempotent: {other:?}"),
            }
        }

        // Skills are installed once, not once per agent: both name the same
        // directory, and doing the work twice would report a false change.
        let shape = l.claude_skills().join("shape/SKILL.md");
        assert_eq!(
            second
                .iter()
                .filter(|a| matches!(a, Action::Skipped(p, _) if p.ends_with("shape/SKILL.md")))
                .count(),
            1,
            "the shared skills directory was visited twice"
        );
        assert!(shape.is_file());
    }
}
