//! Installing the method where Claude Code reads it (DESIGN.md §9).
//!
//! Claude Code is the only target. Other agents were supported here once, in
//! the abstract, before any of them had been used against this pipeline for
//! real — which is how you end up maintaining five renderers that are each
//! wrong in a way nobody has noticed. When a second agent earns its place, the
//! split it needs will be known rather than guessed.
//!
//! What survives that cut is the part that was never agent-specific: the method
//! has one source on disk, and `bevel method shape` prints it. Nothing is
//! transliterated into anyone's prompt format, so there is nothing to drift.

use anyhow::{bail, Context, Result};
use serde_json::{json, Map, Value};
use std::path::{Path, PathBuf};

use crate::method::Source;
use crate::paths::Layers;
use crate::project::Project;

/// Method file names. The bodies live in the method tree on disk, not here:
/// editing a skill must never require a release (DESIGN.md §2).
/// `shape` and `implement` are the lifecycle; the `*-architecture` ones are
/// conventions skills, loaded by the model when the work matches them rather
/// than by a step of the loop. Both kinds install the same way.
pub const SKILLS: [&str; 4] = [
    "shape",
    "implement",
    "rust-architecture",
    "angular-architecture",
];

/// Subagents exist for context isolation: three independent searches that must
/// not pollute the context where the interview happens, and two reviewers that
/// must not have written what they review (DESIGN.md §6, §8).
pub const AGENT_DEFS: [&str; 7] = [
    "domain-scout",
    "risk-scout",
    "unknowns-scout",
    "spec-critic",
    "diff-reviewer",
    "context-packer",
    "mockup-builder",
];

const MARKER: &str = "<!-- generated by bevel — edit the method layer, not this file -->";
const DENY_RULE: &str = "Bash(bevel approve*)";
/// What this tool installed when it was called `harness`. Recognised so that a
/// rename cleans up after itself instead of leaving both generations in place.
const LEGACY_DENY_RULE: &str = "Bash(harness approve*)";
const COMMAND_PREFIXES: [&str; 2] = ["bevel ", "harness "];

// ------------------------------------------------------------------ actions

#[derive(Debug, PartialEq, Eq)]
pub enum Action {
    Wrote(String),
    Skipped(String, &'static str),
}

impl std::fmt::Display for Action {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Action::Wrote(p) => write!(f, "  wrote   {p}"),
            Action::Skipped(p, why) => write!(f, "  skipped {p} ({why})"),
        }
    }
}

/// Install the method.
///
/// `project` is optional because half of this does not belong to a project.
/// What lands in `~/.claude` is the same text on the machine whatever directory
/// you are standing in, so requiring a project first would be a made-up
/// dependency — and one that bites exactly at the moment a new machine has no
/// projects yet.
pub fn sync(
    project: Option<&Project>,
    layers: &Layers,
    source: &Source,
    hooks: bool,
) -> Result<Vec<Action>> {
    if !source.is_usable() {
        bail!("{}", crate::method::missing_help(source, layers));
    }
    // The machine's half first: it is the half that always applies.
    let mut actions = sync_machine(project, layers, source)?;
    actions.extend(sync_project(project, layers, hooks)?);
    Ok(actions)
}

/// Skills and subagents, installed once per machine.
///
/// The split is by lifetime, not by feature. This is the method, and the method
/// is the same text whichever project you are standing in — a copy per project
/// would be N copies of one file, free to drift.
fn sync_machine(
    project: Option<&Project>,
    layers: &Layers,
    source: &Source,
) -> Result<Vec<Action>> {
    let mut actions = Vec::new();

    for name in SKILLS {
        let body = skill_body(layers, source, name)
            .with_context(|| format!("skill `{name}` is missing from the method tree"))?;
        let dest = layers.claude_skills().join(name).join("SKILL.md");
        actions.push(write_generated(&dest, &body, project, layers)?);
    }

    for name in AGENT_DEFS {
        let body = agent_body(layers, source, name)
            .with_context(|| format!("subagent `{name}` is missing from the method tree"))?;
        let dest = layers.claude_agents().join(format!("{name}.md"));
        actions.push(write_generated(&dest, &body, project, layers)?);
    }

    Ok(actions)
}

/// What a project needs said about *itself*, which is nothing at all when there
/// is no project to say it about.
fn sync_project(project: Option<&Project>, layers: &Layers, hooks: bool) -> Result<Vec<Action>> {
    let Some(p) = project else {
        return Ok(Vec::new());
    };

    // The body, in the file Claude Code already loads every turn. One file
    // rather than a file plus a pointer to it: with a single agent to serve,
    // the indirection bought nothing and cost a hop.
    let mut actions = vec![write_if_absent(
        &p.root.join("CLAUDE.md"),
        CLAUDE_MD,
        project,
        layers,
    )?];

    // Project-scoped on purpose, unlike everything in sync_machine: these hooks
    // shell out to `bevel`, and at user level they would fire in every
    // repository on the machine, including those with no project to find.
    actions.push(sync_settings(p, layers, hooks)?);
    Ok(actions)
}

/// A skill body: user layer first, then the method tree.
pub fn skill_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    read_first(&[
        layers
            .user_method()
            .join("skills")
            .join(name)
            .join("SKILL.md"),
        source
            .method_dir()
            .join("skills")
            .join(name)
            .join("SKILL.md"),
    ])
}

pub fn agent_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    read_first(&[
        layers
            .user_method()
            .join("agents")
            .join(format!("{name}.md")),
        source
            .method_dir()
            .join("agents")
            .join(format!("{name}.md")),
    ])
}

/// Either kind, for `bevel method <name>` — which is how the instructions get
/// read without a copy existing in anyone's own prompt format.
pub fn method_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    skill_body(layers, source, name).or_else(|| agent_body(layers, source, name))
}

pub fn method_names() -> Vec<&'static str> {
    SKILLS.iter().chain(AGENT_DEFS.iter()).copied().collect()
}

fn read_first(paths: &[PathBuf]) -> Option<String> {
    paths.iter().find_map(|p| std::fs::read_to_string(p).ok())
}

// ------------------------------------------------------------------ writing

/// Paths as the user recognises them: relative inside the project, `~`-prefixed
/// outside it. Sync now writes to both, and an absolute path in the middle of
/// the output reads like a mistake even when it is not.
fn display(project: Option<&Project>, layers: &Layers, path: &Path) -> String {
    if let Some(rel) = project.and_then(|p| path.strip_prefix(&p.root).ok()) {
        return rel.display().to_string();
    }
    match path.strip_prefix(&layers.home) {
        Ok(rel) => format!("~/{}", rel.display()),
        Err(_) => path.display().to_string(),
    }
}

/// Write a file this tool owns, refusing to clobber anything hand-edited.
fn write_generated(
    path: &Path,
    body: &str,
    project: Option<&Project>,
    layers: &Layers,
) -> Result<Action> {
    let rel = display(project, layers, path);
    if let Ok(existing) = std::fs::read_to_string(path) {
        if !existing.contains(MARKER) {
            return Ok(Action::Skipped(rel, "hand-edited"));
        }
        if existing.trim_end().ends_with(MARKER) && existing.starts_with(body.trim_end()) {
            return Ok(Action::Skipped(rel, "unchanged"));
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    // The marker goes last: these files must open with their frontmatter fence.
    std::fs::write(path, format!("{}\n\n{MARKER}\n", body.trim_end()))
        .with_context(|| format!("cannot write {}", path.display()))?;
    Ok(Action::Wrote(rel))
}

fn write_if_absent(
    path: &Path,
    body: &str,
    project: Option<&Project>,
    layers: &Layers,
) -> Result<Action> {
    let rel = display(project, layers, path);
    if path.exists() {
        return Ok(Action::Skipped(rel, "already present"));
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, body).with_context(|| format!("cannot write {}", path.display()))?;
    Ok(Action::Wrote(rel))
}

/// Add the deny rule and, optionally, the hooks — without disturbing anything
/// else in the file.
///
/// A merge rather than a write: this file is the user's, and clobbering their
/// permissions to install one rule would be a bad trade.
fn sync_settings(project: &Project, layers: &Layers, hooks: bool) -> Result<Action> {
    let path = project.root.join(".claude/settings.json");
    let rel = display(Some(project), layers, &path);

    let mut root: Value = match std::fs::read_to_string(&path) {
        Ok(text) if !text.trim().is_empty() => serde_json::from_str(&text)
            .with_context(|| format!("cannot parse {}", path.display()))?,
        _ => Value::Object(Map::new()),
    };
    let before = root.clone();

    {
        let obj = root
            .as_object_mut()
            .context("settings.json must contain a JSON object")?;
        let permissions = obj
            .entry("permissions")
            .or_insert_with(|| json!({}))
            .as_object_mut()
            .context("permissions must be a JSON object")?;
        let deny = permissions
            .entry("deny")
            .or_insert_with(|| json!([]))
            .as_array_mut()
            .context("permissions.deny must be an array")?;
        deny.retain(|v| v.as_str() != Some(LEGACY_DENY_RULE));
        if !deny.iter().any(|v| v.as_str() == Some(DENY_RULE)) {
            deny.push(json!(DENY_RULE));
        }
    }

    if hooks {
        install_hooks(&mut root)?;
    }

    if root == before {
        return Ok(Action::Skipped(rel, "up to date"));
    }
    std::fs::create_dir_all(path.parent().unwrap())?;
    std::fs::write(&path, format!("{}\n", serde_json::to_string_pretty(&root)?))?;
    Ok(Action::Wrote(rel))
}

/// Three hooks, all of them cheap and none of them blocking.
///
/// Deliberately absent: anything that refuses a write outside `specs/`. It is
/// tempting, but it would break ordinary coding done outside the pipeline, and
/// that is exactly the kind of harness assumption worth not making.
fn install_hooks(root: &mut Value) -> Result<()> {
    let ours = [
        (
            "PostToolUse",
            Some("Edit|Write|MultiEdit"),
            // Reads the hook payload from stdin, so no `jq` is required.
            "bevel fmt --hook",
        ),
        ("SessionStart", None, "bevel status --brief"),
        // Advisory only. A blocking Stop hook can trap an agent in a loop.
        ("Stop", None, "bevel pending"),
    ];

    let obj = root
        .as_object_mut()
        .context("settings.json is not an object")?;
    let hooks = obj
        .entry("hooks")
        .or_insert_with(|| json!({}))
        .as_object_mut()
        .context("hooks must be a JSON object")?;

    for (event, matcher, command) in ours {
        let list = hooks
            .entry(event)
            .or_insert_with(|| json!([]))
            .as_array_mut()
            .with_context(|| format!("hooks.{event} must be an array"))?;

        // Drop any entry we previously installed, so sync stays idempotent
        // without touching hooks the user added themselves.
        list.retain(|entry| !is_ours(entry));

        let mut group = Map::new();
        if let Some(m) = matcher {
            group.insert("matcher".into(), json!(m));
        }
        group.insert(
            "hooks".into(),
            json!([{ "type": "command", "command": command }]),
        );
        list.push(Value::Object(group));
    }
    Ok(())
}

fn is_ours(entry: &Value) -> bool {
    entry
        .get("hooks")
        .and_then(Value::as_array)
        .map(|hs| {
            hs.iter().any(|h| {
                h.get("command")
                    .and_then(Value::as_str)
                    .map(|c| COMMAND_PREFIXES.iter().any(|p| c.starts_with(p)))
                    .unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

/// What this project needs said about itself. The pipeline is here rather than
/// in the skills because it is the part a reader needs before invoking one.
///
/// Loaded every turn, so it is kept under 50 lines and `bevel doctor` says so
/// when it is not.
const CLAUDE_MD: &str = r#"# Agent notes

Non-obvious things only. Anything derivable from the file tree does not belong
here, and nothing here is repeated in another file.

## The loop

Ideas live in `INBOX.md`. Shaping turns one into a spec under `specs/`; a human
approves it; implementation builds it against that spec.

```
bevel status                   where things stand
bevel shape <n>                reserve an id, scaffold specs/NNNN-slug/
bevel validate <id>            deterministic rules; draft -> review
bevel gate <id>                exit 0 if this spec may be implemented
bevel verify --affected        only what changed, plus its dependents
bevel docs <lib> --spec <id>   version-pinned docs from the lockfile
```

`bevel approve` is missing from that list on purpose. It requires a terminal,
so an agent cannot run it. Ask the human, and say what changed.

## Full instructions

```
bevel method shape
bevel method implement
```

Those print the same text `/shape` and `/implement` load, from the one method
tree, so reading them can never disagree with running them.

## Gotchas

<!-- Conventions and traps a competent newcomer to this repo would get wrong.
     Not a tutorial, and not anything the file tree already says.
     Keep this file under 50 lines. -->
"#;

/// Where each method file resolved from, for `doctor`. Without this, "why is my
/// edit not taking effect?" is an afternoon.
pub fn method_sources(layers: &Layers, source: &Source) -> Vec<(String, PathBuf, &'static str)> {
    let mut out = Vec::new();
    for name in SKILLS {
        let user = layers
            .user_method()
            .join("skills")
            .join(name)
            .join("SKILL.md");
        let tree = source
            .method_dir()
            .join("skills")
            .join(name)
            .join("SKILL.md");
        out.push(pick(format!("skill/{name}"), user, tree));
    }
    for name in AGENT_DEFS {
        let user = layers
            .user_method()
            .join("agents")
            .join(format!("{name}.md"));
        let tree = source
            .method_dir()
            .join("agents")
            .join(format!("{name}.md"));
        out.push(pick(format!("agent/{name}"), user, tree));
    }
    out
}

fn pick(label: String, user: PathBuf, tree: PathBuf) -> (String, PathBuf, &'static str) {
    if user.is_file() {
        (label, user, "user")
    } else if tree.is_file() {
        (label, tree, "method")
    } else {
        (label, tree, "MISSING")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() -> (tempfile::TempDir, Project, Layers, Source) {
        let tmp = tempfile::tempdir().unwrap();
        crate::project::init(tmp.path(), false).unwrap();
        let project = Project::discover_from(tmp.path()).unwrap();
        let layers = Layers {
            config: tmp.path().join("cfg"),
            cache: tmp.path().join("cache"),
            // Never the real $HOME: these tests write into it.
            home: tmp.path().join("home"),
        };
        // This repository is itself a method tree, which is what ships.
        let source = Source {
            kind: crate::method::Kind::Local,
            root: std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")),
            origin: "repo".into(),
        };
        (tmp, project, layers, source)
    }

    #[test]
    fn a_full_sync_writes_everything_once_and_is_idempotent() {
        let (_t, p, l, m) = setup();
        let first = sync(Some(&p), &l, &m, false).unwrap();
        assert!(
            first.iter().all(|a| matches!(a, Action::Wrote(_))),
            "{first:?}"
        );
        let skill = l.claude_skills().join("shape/SKILL.md");
        assert!(skill.is_file());
        assert!(l.claude_agents().join("spec-critic.md").is_file());

        let text = std::fs::read_to_string(&skill).unwrap();
        assert!(text.starts_with("---\nname: shape"));

        let second = sync(Some(&p), &l, &m, false).unwrap();
        assert!(
            second.iter().all(|a| matches!(a, Action::Skipped(_, _))),
            "{second:?}"
        );
    }

    /// Claude Code reads personal skills from `~/.claude/skills` and nowhere
    /// else. A skill installed anywhere else looks installed and never loads,
    /// which is the one failure mode with no symptom.
    #[test]
    fn the_method_installs_where_claude_code_reads_it() {
        let (_t, p, l, m) = setup();
        sync(Some(&p), &l, &m, true).unwrap();
        assert!(l.home.join(".claude/skills/implement/SKILL.md").is_file());
        assert!(l.home.join(".claude/agents/domain-scout.md").is_file());
        // Nothing per-project, and nothing in the directory the standard
        // proposes but Claude Code does not read.
        assert!(!p.root.join(".claude/skills").exists());
        assert!(!p.root.join(".claude/agents").exists());
        assert!(!l.home.join(".agents").exists());
        // What is genuinely project-scoped stays behind.
        assert!(p.root.join("CLAUDE.md").is_file());
        assert!(p.root.join(".claude/settings.json").is_file());
    }

    /// What lives in `$HOME` is the machine's, not a project's. Requiring a
    /// project first would be a dependency that does not exist — and it would
    /// bite on a fresh machine, where there is nothing to init yet.
    #[test]
    fn the_method_installs_with_no_project_at_all() {
        let (_t, _p, l, m) = setup();
        let actions = sync(None, &l, &m, true).unwrap();
        assert!(l.claude_skills().join("shape/SKILL.md").is_file());
        assert!(l.claude_agents().join("spec-critic.md").is_file());
        // Every path reported has to be one the user can find without a root
        // to be relative to.
        for a in &actions {
            let Action::Wrote(p) = a else { continue };
            assert!(p.starts_with("~/"), "{p}");
        }
    }

    /// The project half must not be invented from thin air when there is no
    /// project: there is no directory it could correctly be written to.
    #[test]
    fn without_a_project_nothing_project_scoped_is_written() {
        let (t, _p, l, m) = setup();
        sync(None, &l, &m, true).unwrap();
        for stray in ["CLAUDE.md", ".claude/settings.json"] {
            assert!(!l.home.join(stray).exists(), "{stray} in $HOME");
            assert!(!t.path().join(stray).exists(), "{stray} outside a project");
        }
    }

    /// CLAUDE.md is loaded every turn, so it carries the pipeline itself and
    /// pays for it in a budget `bevel doctor` enforces.
    #[test]
    fn claude_md_carries_the_runnable_pipeline_and_stays_in_budget() {
        let (_t, p, l, m) = setup();
        sync(Some(&p), &l, &m, false).unwrap();
        let text = std::fs::read_to_string(p.root.join("CLAUDE.md")).unwrap();
        assert!(text.contains("bevel gate <id>"));
        assert!(text.contains("bevel method shape"));
        // The reason approve is absent has to be stated, or an agent will try.
        assert!(text.contains("requires a terminal"));
        assert!(text.lines().count() <= 50, "{} lines", text.lines().count());
    }

    #[test]
    fn hooks_are_installed_only_when_asked_and_never_duplicate() {
        let (_t, p, l, m) = setup();
        sync(Some(&p), &l, &m, false).unwrap();
        let path = p.root.join(".claude/settings.json");
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert!(v.get("hooks").is_none());

        sync(Some(&p), &l, &m, true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let post = v["hooks"]["PostToolUse"].as_array().unwrap();
        assert_eq!(post.len(), 1);
        assert_eq!(post[0]["matcher"], "Edit|Write|MultiEdit");
        assert_eq!(post[0]["hooks"][0]["command"], "bevel fmt --hook");
        assert_eq!(
            v["hooks"]["SessionStart"][0]["hooks"][0]["command"],
            "bevel status --brief"
        );

        // Running twice must not stack duplicates.
        sync(Some(&p), &l, &m, true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(v["hooks"]["PostToolUse"].as_array().unwrap().len(), 1);
    }

    /// A rename must not leave both generations installed side by side.
    #[test]
    fn entries_from_the_previous_tool_name_are_replaced_not_duplicated() {
        let (_t, p, l, m) = setup();
        let path = p.root.join(".claude/settings.json");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            r#"{"permissions":{"deny":["Bash(harness approve*)"]},
                "hooks":{"Stop":[{"hooks":[{"type":"command","command":"harness pending"}]}]}}"#,
        )
        .unwrap();

        sync(Some(&p), &l, &m, true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        let deny = v["permissions"]["deny"].as_array().unwrap();
        assert_eq!(deny.len(), 1);
        assert_eq!(deny[0], DENY_RULE);

        let stop = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 1);
        assert_eq!(stop[0]["hooks"][0]["command"], "bevel pending");
    }

    #[test]
    fn a_users_own_hooks_survive_installation() {
        let (_t, p, l, m) = setup();
        let path = p.root.join(".claude/settings.json");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            r#"{"hooks":{"Stop":[{"hooks":[{"type":"command","command":"notify-send done"}]}]}}"#,
        )
        .unwrap();

        sync(Some(&p), &l, &m, true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let stop = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 2);
        assert!(stop
            .iter()
            .any(|e| e["hooks"][0]["command"] == "notify-send done"));
        assert!(stop
            .iter()
            .any(|e| e["hooks"][0]["command"] == "bevel pending"));
    }

    #[test]
    fn a_missing_method_tree_is_a_clear_error_not_a_panic() {
        let (_t, p, l, _m) = setup();
        let empty = Source {
            kind: crate::method::Kind::Local,
            root: _t.path().join("nowhere"),
            origin: "test".into(),
        };
        let err = sync(Some(&p), &l, &empty, false).unwrap_err().to_string();
        assert!(err.contains("not available"), "{err}");
    }

    #[test]
    fn method_bodies_are_printable_and_the_user_layer_wins() {
        let (_t, _p, l, m) = setup();
        assert!(method_body(&l, &m, "shape")
            .unwrap()
            .contains("name: shape"));
        assert!(method_body(&l, &m, "spec-critic")
            .unwrap()
            .contains("name: spec-critic"));
        assert!(method_body(&l, &m, "nope").is_none());
        assert_eq!(method_names().len(), 11);

        let src = l.user_method().join("skills/shape/SKILL.md");
        std::fs::create_dir_all(src.parent().unwrap()).unwrap();
        std::fs::write(&src, "custom shape\n").unwrap();
        assert_eq!(method_body(&l, &m, "shape").unwrap(), "custom shape\n");
    }

    #[test]
    fn a_hand_edited_generated_file_is_never_clobbered() {
        let (_t, p, l, m) = setup();
        let dest = l.claude_skills().join("shape/SKILL.md");
        std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
        std::fs::write(&dest, "---\nname: shape\n---\nmine\n").unwrap();

        sync(Some(&p), &l, &m, false).unwrap();
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\nname: shape\n---\nmine\n"
        );
    }
}
