//! Rendering the method into agent-specific locations (DESIGN.md §9).
//!
//! One source, projected outward. Claude Code is tier 1 — skills, subagents and
//! hooks. Everything else is tier 0: `AGENTS.md` plus the artifacts on disk plus
//! this binary, which is enough to run the same pipeline because every phase
//! writes a file and the next one reads it.
//!
//! Deliberately absent: copies of the skills in each agent's own prompt format.
//! `bevel method shape` prints them from the one method tree instead, so there
//! is nothing to drift.

use anyhow::{bail, Context, Result};
use serde_json::{json, Map, Value};
use std::path::{Path, PathBuf};

use crate::method::Source;
use crate::paths::Layers;
use crate::project::Project;

/// Method file names. The bodies live in the method tree on disk, not here:
/// editing a skill must never require a release (DESIGN.md §2).
pub const SKILLS: [&str; 2] = ["shape", "implement"];

/// Subagents exist for context isolation: three independent searches that must
/// not pollute the context where the interview happens, and two reviewers that
/// must not have written what they review (DESIGN.md §6, §8).
pub const AGENT_DEFS: [&str; 7] = [
    "domain-scout",
    "risk-scout",
    "unknowns-scout",
    "spec-critic",
    "diff-reviewer",
    "context-packer",
    "mockup-builder",
];

const MARKER: &str = "<!-- generated by bevel — edit the method layer, not this file -->";
const DENY_RULE: &str = "Bash(bevel approve*)";
/// What this tool installed when it was called `harness`. Recognised so that a
/// rename cleans up after itself instead of leaving both generations in place.
const LEGACY_DENY_RULE: &str = "Bash(harness approve*)";
const COMMAND_PREFIXES: [&str; 2] = ["bevel ", "harness "];

// ------------------------------------------------------------------ agents

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Agent {
    Claude,
    Cursor,
    Gemini,
    Codex,
    Opencode,
}

impl Agent {
    pub const ALL: [Agent; 5] = [
        Agent::Claude,
        Agent::Cursor,
        Agent::Gemini,
        Agent::Codex,
        Agent::Opencode,
    ];

    pub fn id(self) -> &'static str {
        match self {
            Agent::Claude => "claude",
            Agent::Cursor => "cursor",
            Agent::Gemini => "gemini",
            Agent::Codex => "codex",
            Agent::Opencode => "opencode",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|a| a.id() == s)
    }

    /// Tier 1 gets subagents and hooks; tier 0 runs the same pipeline through
    /// `AGENTS.md` and the CLI, losing context isolation but not function.
    pub fn tier(self) -> u8 {
        match self {
            Agent::Claude => 1,
            _ => 0,
        }
    }

    /// A home-directory marker suggesting this agent is installed. Detection is
    /// a convenience, never a requirement — `--agent` overrides it.
    fn home_marker(self) -> &'static str {
        match self {
            Agent::Claude => ".claude",
            Agent::Cursor => ".cursor",
            Agent::Gemini => ".gemini",
            Agent::Codex => ".codex",
            Agent::Opencode => ".config/opencode",
        }
    }

    pub fn installed(self) -> bool {
        std::env::var_os("HOME")
            .map(|h| Path::new(&h).join(self.home_marker()).exists())
            .unwrap_or(false)
    }
}

pub fn detect_agents() -> Vec<Agent> {
    let found: Vec<Agent> = Agent::ALL.into_iter().filter(|a| a.installed()).collect();
    if found.is_empty() {
        // Claude Code is the tier-1 target; rendering for it is the useful
        // default when nothing can be detected.
        vec![Agent::Claude]
    } else {
        found
    }
}

// ------------------------------------------------------------------ actions

#[derive(Debug, PartialEq, Eq)]
pub enum Action {
    Wrote(String),
    Skipped(String, &'static str),
}

impl std::fmt::Display for Action {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Action::Wrote(p) => write!(f, "  wrote   {p}"),
            Action::Skipped(p, why) => write!(f, "  skipped {p} ({why})"),
        }
    }
}

pub fn sync(
    project: &Project,
    layers: &Layers,
    source: &Source,
    agents: &[Agent],
    hooks: bool,
) -> Result<Vec<Action>> {
    if !source.is_usable() {
        bail!("{}", crate::method::missing_help(source, layers));
    }
    // Universal first: this is the portability layer, not a Claude fallback.
    let mut actions = vec![write_if_absent(
        &project.root.join("AGENTS.md"),
        AGENTS_MD,
        project,
    )?];

    for agent in agents {
        match agent {
            Agent::Claude => actions.extend(sync_claude(project, layers, source, hooks)?),
            Agent::Cursor => actions.push(sync_cursor(project)?),
            Agent::Gemini => actions.push(write_if_absent(
                &project.root.join("GEMINI.md"),
                &pointer_stub(),
                project,
            )?),
            // Both read AGENTS.md natively; anything further would be a second
            // copy of instructions that already exist.
            Agent::Codex | Agent::Opencode => {}
        }
    }
    Ok(actions)
}

fn sync_claude(
    project: &Project,
    layers: &Layers,
    source: &Source,
    hooks: bool,
) -> Result<Vec<Action>> {
    let mut actions = Vec::new();

    for name in SKILLS {
        let body = skill_body(layers, source, name)
            .with_context(|| format!("skill `{name}` is missing from the method tree"))?;
        let dest = project
            .root
            .join(".claude/skills")
            .join(name)
            .join("SKILL.md");
        actions.push(write_generated(&dest, &body, project)?);
    }

    for name in AGENT_DEFS {
        let body = agent_body(layers, source, name)
            .with_context(|| format!("subagent `{name}` is missing from the method tree"))?;
        let dest = project
            .root
            .join(".claude/agents")
            .join(format!("{name}.md"));
        actions.push(write_generated(&dest, &body, project)?);
    }

    actions.push(sync_settings(project, hooks)?);
    actions.push(write_if_absent(
        &project.root.join("CLAUDE.md"),
        &pointer_stub(),
        project,
    )?);
    Ok(actions)
}

/// Cursor reads project rules from `.cursor/rules/*.mdc`. One always-applied
/// rule pointing at `AGENTS.md` is the whole integration — duplicating the
/// skills here is exactly the drift this design forbids.
fn sync_cursor(project: &Project) -> Result<Action> {
    write_generated(
        &project.root.join(".cursor/rules/bevel.mdc"),
        CURSOR_RULE,
        project,
    )
}

const CURSOR_RULE: &str = "---\n\
     description: Spec-driven workflow enforced by the harness CLI\n\
     alwaysApply: true\n\
     ---\n\
     \n\
     Follow [AGENTS.md](../../AGENTS.md).\n\
     \n\
     Before implementing anything from `specs/`, run `bevel gate <id>`. A\n\
     non-zero exit means a human has not approved it, and that is not\n\
     something to work around.\n\
     \n\
     Print the full instructions with `bevel method shape` or\n\
     `bevel method implement`.\n";

/// A skill body: user layer first, then the method tree.
pub fn skill_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    read_first(&[
        layers
            .user_method()
            .join("skills")
            .join(name)
            .join("SKILL.md"),
        source
            .method_dir()
            .join("skills")
            .join(name)
            .join("SKILL.md"),
    ])
}

pub fn agent_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    read_first(&[
        layers
            .user_method()
            .join("agents")
            .join(format!("{name}.md")),
        source
            .method_dir()
            .join("agents")
            .join(format!("{name}.md")),
    ])
}

/// Either kind, for `bevel method <name>` — which is how a tier-0 agent reads
/// the instructions without a copy existing in its own prompt format.
pub fn method_body(layers: &Layers, source: &Source, name: &str) -> Option<String> {
    skill_body(layers, source, name).or_else(|| agent_body(layers, source, name))
}

pub fn method_names() -> Vec<&'static str> {
    SKILLS.iter().chain(AGENT_DEFS.iter()).copied().collect()
}

fn read_first(paths: &[PathBuf]) -> Option<String> {
    paths.iter().find_map(|p| std::fs::read_to_string(p).ok())
}

// ------------------------------------------------------------------ writing

/// Write a file this tool owns, refusing to clobber anything hand-edited.
fn write_generated(path: &Path, body: &str, project: &Project) -> Result<Action> {
    let rel = project.display_path(path);
    if let Ok(existing) = std::fs::read_to_string(path) {
        if !existing.contains(MARKER) {
            return Ok(Action::Skipped(rel, "hand-edited"));
        }
        if existing.trim_end().ends_with(MARKER) && existing.starts_with(body.trim_end()) {
            return Ok(Action::Skipped(rel, "unchanged"));
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    // The marker goes last: these files must open with their frontmatter fence.
    std::fs::write(path, format!("{}\n\n{MARKER}\n", body.trim_end()))
        .with_context(|| format!("cannot write {}", path.display()))?;
    Ok(Action::Wrote(rel))
}

fn write_if_absent(path: &Path, body: &str, project: &Project) -> Result<Action> {
    let rel = project.display_path(path);
    if path.exists() {
        return Ok(Action::Skipped(rel, "already present"));
    }
    std::fs::write(path, body).with_context(|| format!("cannot write {}", path.display()))?;
    Ok(Action::Wrote(rel))
}

/// Add the deny rule and, optionally, the hooks — without disturbing anything
/// else in the file.
///
/// A merge rather than a write: this file is the user's, and clobbering their
/// permissions to install one rule would be a bad trade.
fn sync_settings(project: &Project, hooks: bool) -> Result<Action> {
    let path = project.root.join(".claude/settings.json");
    let rel = project.display_path(&path);

    let mut root: Value = match std::fs::read_to_string(&path) {
        Ok(text) if !text.trim().is_empty() => serde_json::from_str(&text)
            .with_context(|| format!("cannot parse {}", path.display()))?,
        _ => Value::Object(Map::new()),
    };
    let before = root.clone();

    {
        let obj = root
            .as_object_mut()
            .context("settings.json must contain a JSON object")?;
        let permissions = obj
            .entry("permissions")
            .or_insert_with(|| json!({}))
            .as_object_mut()
            .context("permissions must be a JSON object")?;
        let deny = permissions
            .entry("deny")
            .or_insert_with(|| json!([]))
            .as_array_mut()
            .context("permissions.deny must be an array")?;
        deny.retain(|v| v.as_str() != Some(LEGACY_DENY_RULE));
        if !deny.iter().any(|v| v.as_str() == Some(DENY_RULE)) {
            deny.push(json!(DENY_RULE));
        }
    }

    if hooks {
        install_hooks(&mut root)?;
    }

    if root == before {
        return Ok(Action::Skipped(rel, "up to date"));
    }
    std::fs::create_dir_all(path.parent().unwrap())?;
    std::fs::write(&path, format!("{}\n", serde_json::to_string_pretty(&root)?))?;
    Ok(Action::Wrote(rel))
}

/// Three hooks, all of them cheap and none of them blocking.
///
/// Deliberately absent: anything that refuses a write outside `specs/`. It is
/// tempting, but it would break ordinary coding done outside the pipeline, and
/// that is exactly the kind of harness assumption worth not making.
fn install_hooks(root: &mut Value) -> Result<()> {
    let ours = [
        (
            "PostToolUse",
            Some("Edit|Write|MultiEdit"),
            // Reads the hook payload from stdin, so no `jq` is required.
            "bevel fmt --hook",
        ),
        ("SessionStart", None, "bevel status --brief"),
        // Advisory only. A blocking Stop hook can trap an agent in a loop.
        ("Stop", None, "bevel pending"),
    ];

    let obj = root
        .as_object_mut()
        .context("settings.json is not an object")?;
    let hooks = obj
        .entry("hooks")
        .or_insert_with(|| json!({}))
        .as_object_mut()
        .context("hooks must be a JSON object")?;

    for (event, matcher, command) in ours {
        let list = hooks
            .entry(event)
            .or_insert_with(|| json!([]))
            .as_array_mut()
            .with_context(|| format!("hooks.{event} must be an array"))?;

        // Drop any entry we previously installed, so sync stays idempotent
        // without touching hooks the user added themselves.
        list.retain(|entry| !is_ours(entry));

        let mut group = Map::new();
        if let Some(m) = matcher {
            group.insert("matcher".into(), json!(m));
        }
        group.insert(
            "hooks".into(),
            json!([{ "type": "command", "command": command }]),
        );
        list.push(Value::Object(group));
    }
    Ok(())
}

fn is_ours(entry: &Value) -> bool {
    entry
        .get("hooks")
        .and_then(Value::as_array)
        .map(|hs| {
            hs.iter().any(|h| {
                h.get("command")
                    .and_then(Value::as_str)
                    .map(|c| COMMAND_PREFIXES.iter().any(|p| c.starts_with(p)))
                    .unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

fn pointer_stub() -> String {
    "See [AGENTS.md](AGENTS.md).\n\
     \n\
     One instruction lives in one place; this file is a pointer so the two\n\
     cannot drift apart.\n"
        .to_string()
}

/// The portability layer. Everything an agent needs in order to run the
/// pipeline without a single agent-specific file existing.
const AGENTS_MD: &str = r#"# Agent notes

Non-obvious things only. Anything derivable from the file tree does not belong
here, and nothing here is repeated in another file.

## The loop

Ideas live in `INBOX.md`. Shaping turns one into a spec under `specs/`; a human
approves it; implementation builds it against that spec.

```
bevel status                   where things stand
bevel shape <n>                reserve an id, scaffold specs/NNNN-slug/
bevel validate <id>            deterministic rules; draft -> review
bevel gate <id>                exit 0 if this spec may be implemented
bevel verify --affected        only what changed, plus its dependents
bevel docs <lib> --spec <id>   version-pinned docs from the lockfile
```

`bevel approve` is missing from that list on purpose. It requires a terminal,
so an agent cannot run it. Ask the human, and say what changed.

## Full instructions

```
bevel method shape
bevel method implement
```

Those print the same text a `/shape` or `/implement` command would load, so the
pipeline works in any agent whether or not it has slash commands.

## Gotchas

<!-- Conventions and traps a competent newcomer to this repo would get wrong.
     Not a tutorial, and not anything the file tree already says.
     Keep this file under 50 lines. -->
"#;

/// Where each method file resolved from, for `doctor`. Without this, "why is my
/// edit not taking effect?" is an afternoon.
pub fn method_sources(layers: &Layers, source: &Source) -> Vec<(String, PathBuf, &'static str)> {
    let mut out = Vec::new();
    for name in SKILLS {
        let user = layers
            .user_method()
            .join("skills")
            .join(name)
            .join("SKILL.md");
        let tree = source
            .method_dir()
            .join("skills")
            .join(name)
            .join("SKILL.md");
        out.push(pick(format!("skill/{name}"), user, tree));
    }
    for name in AGENT_DEFS {
        let user = layers
            .user_method()
            .join("agents")
            .join(format!("{name}.md"));
        let tree = source
            .method_dir()
            .join("agents")
            .join(format!("{name}.md"));
        out.push(pick(format!("agent/{name}"), user, tree));
    }
    out
}

fn pick(label: String, user: PathBuf, tree: PathBuf) -> (String, PathBuf, &'static str) {
    if user.is_file() {
        (label, user, "user")
    } else if tree.is_file() {
        (label, tree, "method")
    } else {
        (label, tree, "MISSING")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() -> (tempfile::TempDir, Project, Layers, Source) {
        let tmp = tempfile::tempdir().unwrap();
        crate::project::init(tmp.path(), false).unwrap();
        let project = Project::discover_from(tmp.path()).unwrap();
        let layers = Layers {
            config: tmp.path().join("cfg"),
            cache: tmp.path().join("cache"),
        };
        // This repository is itself a method tree, which is what ships.
        let source = Source {
            kind: crate::method::Kind::Local,
            root: std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")),
            origin: "repo".into(),
        };
        (tmp, project, layers, source)
    }

    #[test]
    fn claude_gets_skills_agents_and_a_deny_rule_and_sync_is_idempotent() {
        let (_t, p, l, m) = setup();
        let first = sync(&p, &l, &m, &[Agent::Claude], false).unwrap();
        assert!(
            first.iter().all(|a| matches!(a, Action::Wrote(_))),
            "{first:?}"
        );
        assert!(p.root.join(".claude/skills/shape/SKILL.md").is_file());
        assert!(p.root.join(".claude/agents/spec-critic.md").is_file());

        let text = std::fs::read_to_string(p.root.join(".claude/skills/shape/SKILL.md")).unwrap();
        assert!(text.starts_with("---\nname: shape"));

        let second = sync(&p, &l, &m, &[Agent::Claude], false).unwrap();
        assert!(
            second.iter().all(|a| matches!(a, Action::Skipped(_, _))),
            "{second:?}"
        );
    }

    #[test]
    fn tier_zero_agents_get_only_agents_md() {
        let (_t, p, l, m) = setup();
        sync(&p, &l, &m, &[Agent::Codex, Agent::Opencode], false).unwrap();
        assert!(p.root.join("AGENTS.md").is_file());
        assert!(!p.root.join(".claude").exists());
        assert!(!p.root.join(".cursor").exists());
    }

    #[test]
    fn agents_md_carries_the_runnable_pipeline_and_stays_in_budget() {
        let (_t, p, l, m) = setup();
        sync(&p, &l, &m, &[Agent::Codex], false).unwrap();
        let text = std::fs::read_to_string(p.root.join("AGENTS.md")).unwrap();
        assert!(text.contains("bevel gate <id>"));
        assert!(text.contains("bevel method shape"));
        // The reason approve is absent has to be stated, or an agent will try.
        assert!(text.contains("requires a terminal"));
        assert!(text.lines().count() <= 50, "{} lines", text.lines().count());
    }

    #[test]
    fn cursor_gets_an_always_applied_rule_pointing_at_agents_md() {
        let (_t, p, l, m) = setup();
        sync(&p, &l, &m, &[Agent::Cursor], false).unwrap();
        let text = std::fs::read_to_string(p.root.join(".cursor/rules/bevel.mdc")).unwrap();
        assert!(text.starts_with("---\n"));
        assert!(text.contains("alwaysApply: true"));
        assert!(text.contains("AGENTS.md"));
        assert!(text.contains("bevel gate"));
    }

    #[test]
    fn hooks_are_installed_only_when_asked_and_never_duplicate() {
        let (_t, p, l, m) = setup();
        sync(&p, &l, &m, &[Agent::Claude], false).unwrap();
        let path = p.root.join(".claude/settings.json");
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert!(v.get("hooks").is_none());

        sync(&p, &l, &m, &[Agent::Claude], true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let post = v["hooks"]["PostToolUse"].as_array().unwrap();
        assert_eq!(post.len(), 1);
        assert_eq!(post[0]["matcher"], "Edit|Write|MultiEdit");
        assert_eq!(post[0]["hooks"][0]["command"], "bevel fmt --hook");
        assert_eq!(
            v["hooks"]["SessionStart"][0]["hooks"][0]["command"],
            "bevel status --brief"
        );

        // Running twice must not stack duplicates.
        sync(&p, &l, &m, &[Agent::Claude], true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(v["hooks"]["PostToolUse"].as_array().unwrap().len(), 1);
    }

    /// A rename must not leave both generations installed side by side.
    #[test]
    fn entries_from_the_previous_tool_name_are_replaced_not_duplicated() {
        let (_t, p, l, m) = setup();
        let path = p.root.join(".claude/settings.json");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            r#"{"permissions":{"deny":["Bash(harness approve*)"]},
                "hooks":{"Stop":[{"hooks":[{"type":"command","command":"harness pending"}]}]}}"#,
        )
        .unwrap();

        sync(&p, &l, &m, &[Agent::Claude], true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        let deny = v["permissions"]["deny"].as_array().unwrap();
        assert_eq!(deny.len(), 1);
        assert_eq!(deny[0], DENY_RULE);

        let stop = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 1);
        assert_eq!(stop[0]["hooks"][0]["command"], "bevel pending");
    }

    #[test]
    fn a_users_own_hooks_survive_installation() {
        let (_t, p, l, m) = setup();
        let path = p.root.join(".claude/settings.json");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            r#"{"hooks":{"Stop":[{"hooks":[{"type":"command","command":"notify-send done"}]}]}}"#,
        )
        .unwrap();

        sync(&p, &l, &m, &[Agent::Claude], true).unwrap();
        let v: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let stop = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 2);
        assert!(stop
            .iter()
            .any(|e| e["hooks"][0]["command"] == "notify-send done"));
        assert!(stop
            .iter()
            .any(|e| e["hooks"][0]["command"] == "bevel pending"));
    }

    #[test]
    fn a_missing_method_tree_is_a_clear_error_not_a_panic() {
        let (_t, p, l, _m) = setup();
        let empty = Source {
            kind: crate::method::Kind::Local,
            root: _t.path().join("nowhere"),
            origin: "test".into(),
        };
        let err = sync(&p, &l, &empty, &[Agent::Claude], false)
            .unwrap_err()
            .to_string();
        assert!(err.contains("not available"), "{err}");
    }

    #[test]
    fn method_bodies_are_printable_and_the_user_layer_wins() {
        let (_t, _p, l, m) = setup();
        assert!(method_body(&l, &m, "shape")
            .unwrap()
            .contains("name: shape"));
        assert!(method_body(&l, &m, "spec-critic")
            .unwrap()
            .contains("name: spec-critic"));
        assert!(method_body(&l, &m, "nope").is_none());
        assert_eq!(method_names().len(), 9);

        let src = l.user_method().join("skills/shape/SKILL.md");
        std::fs::create_dir_all(src.parent().unwrap()).unwrap();
        std::fs::write(&src, "custom shape\n").unwrap();
        assert_eq!(method_body(&l, &m, "shape").unwrap(), "custom shape\n");
    }

    #[test]
    fn a_hand_edited_generated_file_is_never_clobbered() {
        let (_t, p, l, m) = setup();
        let dest = p.root.join(".claude/skills/shape/SKILL.md");
        std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
        std::fs::write(&dest, "---\nname: shape\n---\nmine\n").unwrap();

        sync(&p, &l, &m, &[Agent::Claude], false).unwrap();
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\nname: shape\n---\nmine\n"
        );
    }

    #[test]
    fn agent_ids_round_trip_and_tiers_are_assigned() {
        for a in Agent::ALL {
            assert_eq!(Agent::parse(a.id()), Some(a));
        }
        assert!(Agent::parse("emacs").is_none());
        assert_eq!(Agent::Claude.tier(), 1);
        assert_eq!(Agent::Codex.tier(), 0);
    }
}
